// alert('clues');
CLUE= new Array(
"Forsake careless freedom",
"Leave a musical group playing",
"Uninhibitedness when musicians are playing",
"One who helps a superior, we hear",
"One who helps a superior, we hear",
"The maid's a huge worry",
"We can do with it!",
"Recanted about rude jab",
"Shorten a game of cards",
"Shorten a game of cards",
"Shorten a means of getting to the other side",
"Shorten a river crossing",
"Shorten a viaduct",
"Release sailor to find the answer",
"Don't vote for sailor who has blemish",
"To the sailor, it's an awful thing not to indulge",
"Agrees to have a couple of hundred different pets",
"Bill will produce a report",
"He charges a couple of hundred to the employer",
"One who points the finger cares about protecting copper",
"One who points the finger cares about protecting copper",
"Priest's attendant with clay toe!",
"Obtain a group of singers, we hear",
"Discharges an account and leaves",
"A measure of space and time",
"Extent of land needs unusual care over a long time",
"Circus performer who travels by air, car and boat perhaps",
"Casters could well upset her",
"Does she receive part-payment",
"Her work falls into parts",
"Direct mail",
"It indicates the destination and could be delivered as part of the service",
"Speech and attire of modern times",
"Speech might indicate where one's home is",
"Stuck in this place with a theologian around",
"Shared but clings",
"Mad liar maybe, and a master of craft",
"One who goes to court?",
"Go ahead and give someone money",
"Make progress on borrowed money",
"Opposing a dunderhead having little Diana's place in 4 (diverse)",
"...and they provide information of present day bad habits",
"Once more on the street in opposition",
"Everlasting description of those who stay young longer",
"Advocate riotous living?",
"Ian's ego will suffer as a result of character change",
"In age so twisted, suffering pains",
"A good reason for being stranded",
"A reason for being on the rocks, perhaps",
"A reason for being stranded",
"Complaint about meal-tin",
"Crack performers in top-rate speed contests (3,4)",
"I heard alert, sir – it's necessary to divert to this! (3-4,7)",
"It's stuffy having no-one to succeed, we hear",
"Elevator with no earthly connection?",
"Overhead lines",
"Broken treadle had a warning notice",
"Used by mathematical men of letters",
"His enemies got fatally jarred",
"Gets off with a slight dislocation",
"Crooked dealing straightened out",
"Lively supporter in oral composition",
"Everybody due to be paid gave permission",
"Let everyone with a ring get married",
"Permitted the lot to be payable",
"No realm should be upset by a social worker",
"She gives patient advice on social problems",
"Gets together for the service when marooned by rising sea",
"He gains nothing but pleasure from his activities",
"Heather, following in the morning, reaches a Continent",
"Can I be good-tempered",
"Can I be lovable",
"Can I be so friendly",
"Can I provide a friendly solution?",
"A name is confused – memory's at fault",
"It will confuse men in a certain continent",
"Miserable men stuck in continent when past life gone",
"A pondering that's funny",
"Hardly a full-blooded complaint",
"It may make people turn pale",
"A prison on the move",
"It can be worked out by the letter sorter",
"An expert in breaking down any salt",
"He breaks down when at work",
"Roguish in any state of chaos",
"Perhaps to many a branch of medicine",
"Old Shakesperian ensign",
"A musical term and a type of bet",
"Road ran to mountain republic",
"Somehow name a single flower",
"Wrongly name a single flower",
"Made very cross, enraged perhaps",
"Terribly enraged",
"They use rod and line right in the corners",
"Lean at an angle",
"Enliven a team in disorder",
"To a man I change direction on how to play a lively part",
"i.e. Danes produce this flavouring",
"In a bad temper the day none came round",
"A night in France cuts into any kind of regular income",
"Rawness can produce the wrong ones",
"Rise for the workers? (3-4)",
"Capsize a tug in a West Indian island",
"A strange notion for the Merchant of Venice",
"He's not a particular person",
"He's not a particular person",
"No specific occasion when there's a tiny change by me",
"After getting in the beer he went round preaching",
"Somehow stop ale for the evangelist",
"Clothing of unusual appeal's about right",
"Strange pal about to peel off clothing",
"Pacify primate about vegetables",
"Makes use of one in fruit",
"Designate father to get back to the subject",
"Gives somebody the job – one liked with decimalisation, by the sound of it",
"Fruit transported to Capri",
"A question put to a tailless mite living in water",
"Strong light to alarm P.C. Maybe (3-4)",
"Old broken chair included in the account",
"Hear cry about 3's sport?",
"There's a powerful drawback to this sport",
"Bending to make superior gin cocktail",
"Shrewd method of making rustic feature",
"A dour disposition is, to us, hard to bear",
"A marine arrangement for region of Western Asia",
"Stimulated to use a rod perhaps",
"Fix the score to suit the players",
"Organise an island, for example, coming up....",
"Plan to make nag rear",
"Checks what the police make",
"Learns a weapon store has been wrecked",
"Shockingly endless increase in poison",
"What one may write about a recital",
"Possibly train as a mechanic",
"Trains a factory operative differentially",
"Trains a workman redeployed",
"The performer tears it apart",
"This performer may give it a rest",
"He shuns society and sounds vinegary",
"On which the remains of the weeds will be deposited (3-4)",
"Feeling the cold – a southern winter in France needed",
"As stupid as one having one over the eight!",
"Almost hoping for a pain-killer",
"Endlessly longing for a headache cure",
"Sold by chemists in Paris, perhaps",
"Use violence on a sailor, we hear",
"Use violence on a sailor, we hear",
"Agrees to being dispatched in a ship",
"Obtain a group of singers, we hear",
"Helps a donkey – sits awkwardly",
"Calm beast of burden on university time",
"Puts it on without being told",
"Puts it on without being told?",
"Puts it on without being told?",
"Some of the ballerinas to understand how to cause amazement",
"Apart, like below",
"Something to be paid for a Tom backing round street",
"Being risked (like Joan of Arc?)",
"He doesn't believe this tea is blended!",
"Let heat out on the track, perhaps",
"The late converted into the quick?",
"The late converted into the quick?",
"An abstainer finishes and waits on",
"Turns up and listens",
"Turns up and listens",
"Lots go here",
"Where lots go despite rising prices",
"His is a search examination, by all accounts",
"One who hears and sums up all the accounts",
"One who listens to the accounts?",
"Possibly unite as kinswomen",
"It's both simple and hard at the same time",
"South wind goes to the east and becomes harsh",
"Could be about United States transport",
"Helped Ada live wildly",
"Caviare might produce such greed",
"Caviare might produce such greed",
"Caviare might produce such greed",
"Greed for caviare spread",
"It's mean to keep a girl in such a long time",
"It's mean to keep a girl in such a long time",
"Mean girl in just in time",
"Mean girl is just in time",
"Mean to state how old one is",
"To declare one's time of life – that's mean!",
"Affirm Edward prevented",
"Graduate is next to learner on the way to the city",
"Half London to an infant in an ancient city",
"Hold back in favour of wild animalWithdraw since defender is no longer in the team",
"Gamblers who make no progress",
"Financially, and otherwise, ie enables you to stand on your own feet",
"It's used for weighing a kind of sheet",
"Youngster in charge of the bounders in court!..(4,3)",
"The gang spotted the woodcutter",
"They prohibit devices used in the demonstration",
"Possibly a bit past it might describe John",
"Haggle for profit from drinks?",
"Girl in public service?",
"Bombardment results from storm in the drinking-place",
"Obtains different defence",
"Somehow obtains reliable defence",
"Putting up with a certain appearance",
"People retire to it from boredom",
"Where those who lie are bolstered up",
"Bengali changing nationality",
"Give credit?",
"How the bull gets the fire burning",
"Roars to get the file roaring",
"What a bull can contribute in the blacksmith's shop?",
"Bewildered, finding birds in bed!",
"Been ridiculously well as advantage",
"Fine bet brings profit",
"It's a blessing only one nib's broken",
"Be valued but harshly scolded",
"Obligatory process in book production",
"Went like a lamb, but badly late in bed",
"Flower for some unambitios people",
"Flower proved to be a bad mistake",
"This flower proves to be a bad mistake",
"Does he go on a ship for lodging?",
"One who prepares for the voyage as a paying guest",
"Support lobster salad",
"The hobo sir, is horribly ill-mannered",
"The hobo sir, is horribly ill-mannered",
"Ennui in the bedroom",
"Lack of interest in redesigning the bedroom",
"Untidy bedroom shows lack of interest",
"Takes advantage of somebody who makes advances?",
"Imposed limits on what vaulters did",
"Does it produce cartons for fruit",
"Crowed when the head of Biology gets teased",
"For the present one may go for a dip in it (4,3)",
"Such goods can be identified and produced all round",
"The money that is needed for a golf club",
"How wide is loaf with the end cut off?",
"Go to pieces when the short stoppage is over?",
"A smashing wave",
"Army group from 4",
"Robber provides equipment in the gang",
"One of many used in brushwork",
"Inclined to be snappish",
"Rich fabric with an outstanding design",
"A relative right in the midst of trouble",
"Paid for right inside and carried back.",
"He presumably has a constructive outlook",
"Nude in poor act in cafe show",
"Nude seen in new act in the floor-show",
"In such agreemenrs cash, too, is involved",
"Means of gauging a boring job",
"Necessitate being collected? (4,3)",
"Order to strike – as the line-judge may do (4,3)",
"He issues a summons to those due to appear (4-3)",
"Crying out for a vocation",
"Being hardened, a summons is nothing to us",
"Visits and enlists someone's help (5,2)",
"Where you'll find Arthus arrived with many more",
"Frank article written by G. B. Shaw",
"Weep about girl from tinning factory",
"Men of the cloth, one hears, are big boomers",
"3 [FUNDS], perhaps involving loss of life",
"A great character",
"A splendid city",
"Investment in the chief city",
"Strange meal brought by vehicle – its sweet",
"Vehicle is really a vehicle towed by another",
"To be concerned about container for firearm",
"Formally approved what the porter did",
"Cases not put back in vehicles",
"Funny drawing box with nothing inside",
"Prepare to sail away after the players (4,3)",
"Actors on strike rejected",
"What happened when the actors moved first at chess?",
"Stuffy complaint",
"Having come from the terrace, he sees to the customers' needs",
"It sees or can be seen in the dark (4-3)",
"Auction arrangement causes wariness",
"Many make certain you get the blame",
"Horseman may give an ace turn",
"Nice art for sure",
"Annoyance at being endlessly in charge?",
"Took the meeting and was carried off triumphantly",
"Alterations in the bell-ringer's programme",
"Gets into different gear!",
"Pipe of pipes",
"Padre dropped a comic",
"It's associated with verse in giving the exact reference",
"Not a free horse",
"Allegations which are not freely made?",
"100 hurt under a spell",
"Final word of encouragement I love",
"Sounds like one tricks a wild animal",
"Put a chit in for wine",
"Smartly dressed in the past in America",
"Break into a conversation as a bell might do at home",
"It's an illusion that many take a long time after him",
"Its contents are tapped by washers",
"Idle act in the fortress",
"Keep lad- cite the difference",
"Loud complaint of 150 having love affair",
"Outcry about beginner with love in Paris",
"Outcry about beginner with love in Paris",
"Given rank in school?",
"100 girls split into groups for teaching",
"Gives rise to about fifty sections of an agreement",
"Leer can upset char",
"More hygienic charwoman",
"Settled the bill and made a profit",
"Obviously 150 are more than punctual",
"One who holds on to the hatchet",
"The mountaineer rose",
"Sets of crossword indicators with intelligence quotient included",
"100 being beaten to finish with",
"Look in untidy chest for apparel!",
"The colt she turned out provides coverings",
"Plants fifty in part of a cricket field",
"Beaten by one particular suit?",
"A hundred proposals for making money-boxes",
"Assemble for a little prayer",
"A producer and transporter of coal",
"Dog is right for miner",
"Agreement found in lady's handbag",
"Direction-finder in space",
"The scope of a direction instrument",
"Firm politicianis first on before he introduces acts",
"He tells you whose turn is next",
"To hide on one occasion in short visit",
"Affair that will worry you?",
"Firm interest",
"Worry about the affair.",
"The composition lacks nothing for the musical performance",
"Sounds like an aircraft agreement",
"Sounds like an aircraft agreement",
"Guide one's behaviour",
"Wield the stick in time to get behaviour",
"Do the coventional thing and study how the horses run",
"Comfort on the organ?",
"Study kind husband",
"Study diplomacy in meeting",
"Touch study with diplomacy",
"No, I can't vary what receptacles do",
"Strive to put 100 on 10 with 500 more",
"Happy with the substance",
"Study temporary dwelling to be happy",
"100 being tried in competition",
"100 being tried in competition",
"The first of the criminals on trial to question the facts",
"Geographical line for a hundred on trip",
"Outline of a number travelling about",
"Outline of a number travelling about",
"Outline of a number travelling about",
"Unconventional inclusion of religious community",
"They reduce the temperature in prisons",
"Policemen make very little money",
"The commanding officer and Clare upset the boat",
"Not rich in Greece",
"He inquires into unexpected departures",
"Pirate with a rough manner, one hears",
"Train one is usually late for",
"An odd custom with Eastern dress",
"The company must change eastern dress",
"Calculator fitted into a shop",
"Tripping out of town (7-7)",
"A brilliantstroke allowed in poetry",
"Short rhyme upset by Colet",
"There's a rider to it: there's nothing in somebody who swears",
"Held up by a gunman – but insured!",
"Held up by the gunman but protected",
"Made yourself fearfully small?",
"Neat attendant",
"Neat drover",
"Little credit remains in disasters",
"Does something original and causes a fuss",
"Makes a fuss when a secret is ruined",
"makes something new of set race",
"A first-former?",
"Ivy's an obsequious type",
"Ivy's an obsequious type",
"No quick-growing plant?",
"Virginia's stealthy one",
"Fair game?",
"Sporting jumper",
"100 on edge over boy going red",
"Class initially on edge with boy going red",
"Dishonest in possessing bishop's or shepherd's staff",
"A barber no-one wants to come",
"Downfall of a barber",
"Downfall of a barber?",
"Changed sides, as the voter did",
"Gets over life's burdens",
"Boasting 100 at the oars",
"Boasting 100 at the oars",
"Piece of bread the French break into bits",
"Weep over last broken glass",
"Likely to be resolved by physics",
"Keeper has a dog on the hill",
"Fruit ran short outside",
"Watercourse on view at the moment",
"Cut short what a dog wags?",
"Its fall could ruin act",
"Window dressing described in brief article at home",
"A really sharp and hurtful piece clipped from a newspaper",
"Nice day upset by poison",
"It gets the wind up in a roundabout way",
"Everybody in disorganised side moves idly",
"Beloved family created by Barrie",
"Going at full speed and breaking to pieces",
"The cemetry? There's only one way out of this(4-3)",
"The cul-de-sac all mortals reach",
"Expired Greek god is quite expressionless (4-3)",
"It's most expensive, darling",
"There's nothing more expensive, darling",
"Lowered the dignity of graduates indeed!",
"Makes off wih the tents?",
"Settling point",
"Settling point",
"There's some point in this system",
"Make a speech against decimal conversion",
"Get cleared in order to follow the Cusom officer's advice",
"Refuse to become senile",
"Refuse to show signs of senility",
"Refuse to show signs of senility",
"Refuse to sink",
"Turn down slide",
"Unusually rum code of behaviour",
"Put down in a legal document that it's deferred",
"Indeed a cancelled service should be",
"The fault of rough tide round the French sea",
"Even a contented one would look down in the mouth",
"First of all he's an expert in oral examinations",
"Mouth-piece",
"Appointed place in a legal document",
"Main in a whirl – engine fuel his trouble?",
"River in which a wader went to fish",
"Part of the song heard over the air",
"Drop of French perfume",
"Wastes the rewards",
"Wastes the rewards",
"Be entitled to rout Ford in 22 (reserve)",
"Draughtman's intentions?",
"Draughtsman's intentions",
"Draughtsman's intentions?",
"Draughtsman's intentions?",
"Hopelessness I spread around",
"I spread hopelessness",
"The hopelessness of the French couple",
"It comes last, locked in reverse",
"Leaves from arid areas",
"Tried to reform a U. S. City",
"Tried to reorganise part of Michigan",
"The talk of the district",
"Everybody inside expired – tried to get a 'phone number",
"He wrote the – of a lot of novels",
"Give the text of a letter, as tyrants do",
"An obstinate person had dire trouble (3-4)",
"Poor side away from home becomes extinct (4,3)",
"Spread far and wide, it feuds become disorderly",
"Tidying noble bearing",
"People with such depressions may still look happy",
"Make out cinders",
"Perceive Cinders is upset",
"Seek various opinions on records about America",
"Dad is wrong in showing contempt",
"Did a sin bring scorn",
"Don't approve but is liked somehow",
"Don't approve but is liked somehow",
"Number I spread out for show",
"The show consists of underworld drama",
"The show consists of underworld drama",
"Arrange to get rid of",
"Arrange to get rid of",
"Being placed in different side will lead to argument",
"Don't agree when Diana's told to go",
"This side of the family is female",
"Songs said in France to have certain obligations",
"I'd written up poetry that's different",
"Unlike 501, replaced again in 1 (1 IS reserve)",
"Heavenly body follows the sailor and the sailor follows it! (3-4)",
"Foreign girl to perform different roles",
"Fellow given solutions tp the beasts",
"Walked back around a man sleeping",
"Walked back around a man sleeping",
"Cavalryman to continue tediously round the ring",
"There's nothing in mythical monster for cavalryman",
"Materials in business?",
"A drink for a man on board",
"Elicit that the raffle result has been announced(4,3)",
"China reddens somehow",
"Get ready for the carnival and frock of martydom (5,2)",
"Piece of furniture of great help to the actress back-stage",
"Gets ready to eat, or to be eaten",
"Suits oneself",
"He can't do without glasses",
"In such rain; it's better than walking",
"Rejected from the team – collapsed",
"Where there's no bar for ship repairers? (3,4)",
"Harasas the debtor gone somehow underground",
"What bad rule is not easily got rid of?",
"Stand up perhaps to receive the sweep (4-3)",
"Could beating it lead to deafness (3-4)",
"Listener's complaint",
"Rank with an old mare, perhaps?",
"Ardent enough to gain entitlement to set out",
"Serious Eastern muddle",
"Getting in range, perhaps",
"An ornament attached to a sound receiver",
"You're in a sound position in this",
"Buried as a safety precaution",
"Protected from shock, though broken-hearted",
"Nearest oriental disturbance",
"Nets are oriental",
"Point behind the ship towards the sunrise",
"Period of maritime decline (3-4)",
"A heavenly intervention?",
"Yes, acts in variety will produce great delight",
"Boy mixes gin, going round in circles",
"One impression produced by journalists",
"Newspaper men become so tired!",
"Exertions in brief for tsars",
"Drink to encourage loud insolence",
"Too much self-expression",
"A bouquet for Judy",
"One would feel put out to be treated so",
"Pal sees a mix-up and slips away",
"Turns pale to begin with, but it passes",
"Cat lies in trouble; stretcher needed",
"I am put in a ruined castle for a stretch maybe",
"In ruined castle I will return after a stretch",
"Salt and ice in flexible combination",
"Salt and ice in flexible combintion",
"Great joy in breaking toenail",
"High spirits making a member of the family lose his head",
"It alone can provide a sense of euphoria",
"She has one real potential",
"...role etc., of person in polling",
"Chosen or chooser",
"He will cross anybody he chooses",
"Parties appeal to him",
"Role, etc., for the voter",
"A first principle in current heaters",
"Basic part of an electric kettle",
"Basic part of an electric kettle",
"Use live reconstruction – that's dodgy!",
"Ban could rob game",
"It cancels any sailing order",
"Stop and go after amber changes",
"Stop and go after amber changes",
"Hold in great affection",
"Hug and bring up note to the couple",
"Include in a show of affection",
"Take to arms!",
"A feeling of Easterly movement",
"A feeling of Easterly movement",
"Feeling aroused by proposal from the East",
"Possibly omit one sort of transport",
"Eatern impulse causing strong feeling",
"Authorise me to return with force",
"Give authority to a rising Middle East nation",
"Might follow me up to authorise",
"Rival bird is not on time",
"Makes it possible for some to open a blessed long time",
"Charm belonging to us following change of name",
"Can be, in changing, hold fast?",
"Do some spelling?",
"Sing in French first to delight",
"Mate wanted here",
"Descriptive of anythingh that shows no determination?",
"Like an eternity ring",
"Smaller at the finish, yet never finishing",
"Sanction conclusion; rose is poor",
"Bequeathed when finally was in debt",
"Being safe in the end is guaranteed",
"He lasts out and reaches the finish first",
"Sticks it out, but rues badly at the finish",
"Survives to the finish with sure arrangement",
"Puts the sheep to bed?",
"Hired as future partner?",
"Liked producing happiness in dreadful need.",
"Add to the general confusion",
"Add to the general disorder",
"One way to make a big picture",
"Officers sensing change",
"Officers sensing change",
"Made certain the user is put right in the finish",
"Give one the right name",
"Give one the right to name a book",
"Competitor who's no outsider",
"One of the new 'in' crows?",
"Beg for a chance in the net rate",
"Competitors make attempt on two points",
"Jealous due to new oven one gives to us",
"Man of taste might rue alteration to long poem",
"Pie cooked to  heal food-over",
"Ifthe letter is upsetting, sleep it off",
"Letter that is spelt badly",
"Unusual spite shown to the French in a letter",
"A form of commendation gravely written",
"Message with a grave association",
"Woed described the pet I replaced",
"Making noise or wearing away",
"Noise or disturbance can be wearing",
"Irregular crater erupts about one",
"Ran away in headgear covered in scattered seed",
"Grass around the seaport",
"Personal property in Orental kingdoms",
"Real net lasting for ever",
"Girl given hint easily at first to be one escaped from danger",
"Avoidance of tax? No I save up!",
"Dodging questions about the odd vase I have",
"I have to save up first – that's dodgy",
"An occasion for mass attendance before bedtime (7,7)",
"Balance used in eleven supermarkets (5,2)",
"Severe problems to start trying to reach the summit",
"Severe strains revealing what is most difficult to scale",
"The height of a severe storm",
"Favourite we take the wretched blame about!",
"He compels payment from a retired performer",
"Formerly enough for a specimen",
"Specimen was formerly sufficient",
"Out of work one may take it",
"Use up supplies of a car accessory",
"Use up supplies of car comonents",
"Cost of river flowing round enclosures",
"Cost price",
"Elucidate what was formerly clear",
"Goods sent abroad from harbour towns",
"Former soap mystery left on display",
"Unmasked once one asked questions",
"Make a statement formerly in the newspaper?",
"A piece taken from previous religious paper",
"As far as one can go to meet Rex",
"Going to great lengths at either end",
"Last but not least",
"The point where nothing further can be expected",
"The point where nothing further can be expected",
"Describing the pupil showing no sorrow",
"We say he is upset by humbug (3-4)",
"Bereft of pupils",
"Don't stare so much; must be blind",
"Let's look first at some openings",
"Looks at the mineral – what a hideous sight",
"It clears the vision, but deceives the judgment",
"Contentious party demanding loud, dramatic movement",
"Dissention producing loud lawsuit",
"First-class in pitch to a fault",
"Good route for long-distance driver",
"Passable method golfers should keep to",
"Passable method golfers should keep to",
"Quite a considerable distance to the hole",
"Quite an appreciable distance drivers try to cover",
"Not to agree to a full distribution (4,3)",
"It's a fly – that could be a misleading statement",
"Not near the lines of piglets",
"Sounds like Dad means to be more distant",
"It's an accomplishment with her light weight",
"Running a temperature – cause irritation after the second month",
"Enclosing an area for sword-play",
"Enclosing an area for sword-play",
"Passionate rewriting never seen in the Financial Times",
"Fancy work?",
"Fancy work?",
"Nero?",
"Nero?",
"Shooting stars",
"Inspire worker to be the opposite of an arsonist",
"Examine after an attack – expected to survive",
"When people may collect in the street",
"Gave a signal but grew languid",
"Alight as a tailless bird!",
"To give undeserved praise is more monotonous",
"Acquires feathers for flying – flying start on ridges of rocks",
"On air journey, youth leader becomes giddy",
"Loudly mooing and moving gently along",
"Handles with care",
"Mental sustenance (4,3,7)",
"It's stupidity – even without Tom",
"Looked for food on behalf of old people",
"Goes far and looks for food",
"Be patient because of wild animal",
"Overseasw gin upset at the front",
"The enemy is about right: he's in charge",
"In favour of mixed sets of woods",
"It is put down after offer is revised – that's fine",
"Fake produced by a blacksmith",
"Fraudulent imitation in the blacksmith's shop?",
"Chance for a bit of music",
"The one who started it will go under",
"Weak piece of material in documentary system",
"A precious possession one is not bound to have",
"No payment required by the Poruguese for liberty",
"One is at liberty to enjoy this state",
"Scare about eastern cargo",
"If Fred's in trouble he may well need them!",
"People who make a lot of them are popular",
"Equipment in what must be a warship",
"A waste time on battered food",
"Squander food?",
"It's delivered after somebody has departed",
"Amusements and sideshows mostly one-sided",
"Amusements mostly one-sided",
"Supply vessel surrounded by fish",
"Bitterness associated with an age old craft",
"Bitterness associated with an age old craft",
"Largely where art may be displayed",
"Even as loser,he's still better",
"He takes chances in his occupation",
"Rubbish sack in French railway terminal",
"Straight assortment of stones",
"Unusually strange stones",
"One could be faced with this protection against dangerous inspirations! (3-4)",
"It could be used to make a getaway!",
"Collects in the rags, perhaps",
"Enlarge widespread epithet in variety",
"Furniture used by actor preparing to go on stage?",
"Military commander isn't particular",
"Not a specific officer",
"Officer in uniform or overall",
"Officer who is not particular",
"Conference of brass-hats held annually",
"Mr Kelly's in the first book",
"Refined fellow, slippery fish.",
"Refined male fish?",
"It's true it will upset the ingenue",
"Go a step towards making  secret police force",
"Police organisation gets a petty-officer in trouble",
"Find a means to escape (3,4)",
"Obtain a method of escape (3-4)",
"Come by a method of escape",
"They should get one into hot water",
"They supply hot water, naturally",
"An animal unlikely to be overlooked",
"Animal which narurally has the best view!",
"Ruth upset general",
"Shine – like rubbish at Gateshead",
"Gin and choc mixture consumed in Italy",
"Gin and choc mixture consumed in Italy",
"Attempt to pocket a ball, but lose one's nerve? (2,2,3)",
"Bolts like a turkey?",
"A welcome surprise as dogs run to the finish",
"A type of rock from Tangier",
"Rock in great variety",
"Tearing the rock apart",
"Told tales as one prepared the lawn",
"Set of bars that irritate",
"It is put into sauce for meat in all seriousness",
"Lubricant boat-worker?",
"Rearrange a garden in the West Indies",
"Badly angered by explosive device",
"Distorted expression when I'm in prayer",
"The expression of a tight-lipped expert",
"Held one's interest",
"Justification for sports",
"A line in gold showing age (4,3)",
"Given protection, being cautious",
"Given protection, being cautious",
"Had a shot at the visitor, one hears!",
"Have a shot at the visitor, one hears!",
"They have no settled occupation",
"It's usually done at home",
"Didn't lack a place to land the fish",
"Owned a place to land fish",
"A shortening of capital cover! (4-3)",
"Lock lubricator",
"Lock lubricator(4-3)",
"It keeps locks in order",
"Used to make a lock fast, or to pick it",
"The moron is not a complete humorist",
"Those who pull up neck-ties!",
"Hinders production of baskets",
"Worker away from home given leaflet",
"Worker away from home given leaflet(4-3)",
"It's unfortunte if she gets involved with pals",
"Rebuilt bar in time to provide shelter",
"Unyielding and difficult games on the tennis court (4,3)",
"Callous group, having completely lost fluidity (4-3)",
"Gear to make use of horse-power",
"Gear to make use of horse-power",
"His part is arranged for a member of the orchestra",
"One from the past is still here?",
"Has a row, being more impetuous",
"Yes he'd a scattering of grass fragments",
"Title indicates the direction being taken",
"Receiving information of a trial",
"Learn to tell rumour",
"Encourage to listen to half the score",
"Ah, there is different moorland plant",
"Because she's cold?",
"He gets a countermand to stop at sea (5,2)",
"Female with prospects",
"Female with prospects",
"Leading characters gives drug to egghead",
"The girl on the railway will make a place for waders!",
"A retreat to conceal away from home (4-3)",
"Skin removed in place of concealment",
"Head wear for the arrogant",
"He's about to irritate with temporary stoppages",
"Sole reinforcement",
"Supports yet doesn't allow to proceed (5,2)",
"The money that is for the golf club",
"Approves of indications of support",
"Home Office breaks the mould in search for a gangster",
"An entertaining lady",
"She entertains those upset on the ship",
"Describing the enemy army with a shocking lie",
"Pot shot to provide food",
"He got out a lot to entertain",
"Bone smell sure is bad",
"Bone smell sure is bad",
"Funny moods?",
"Aging leader in famished country",
"Empty except for a country",
"Very eager about a country",
"Right-winger gets hurled around by a sportsman",
"They hang about in the cold",
"Idly moved before being left in charge – how blissful",
"Base involving fifty in Boeing crash",
"Maltreated by being employed when unwell? (3-4)",
"It's forbidden, and badly one hundred take it",
"Fancy aiming to turn to the east",
"Fancy having an idol lying around at home!",
"It is taken by one colleague to copy",
"You'll find me in dilapidated mines of great size",
"Put into liquidation?",
"Put into liquidation?",
"Reveals I am to get the strap back",
"Arraign him disturbed about endless peace",
"Dive? I am favourite on way to America",
"Touch on what brought Zulu warriors to a strange end",
"Insinuating one politiciandidn't tell the truth",
"Given the impression that mischief decorates the truth",
"Being enjoined, I am ready to be photographed",
"It will create quite an effect when I am a reporter",
"I'm the type to make an impression",
"I'm the type to make an impression",
"Stamp I'm to put on paper",
"Briefly win road",
"Sort of study carried out by bathyscape (2,5)",
"Foolishly altering any line that's not straight",
"Kind of ship's motor made of bad iron",
"Anger at fashionable scene being trashed",
"Anger with spicy smoke",
"Anger, even if it does smell sweet",
"Could its odour make worshippers angry?",
"Is it the smell that makes people furious",
"Perfume made to provoke",
"Smouldering anger?",
"Smouldering anger?",
"Caused provocation in unusual edict",
"Roused at home, before being quoted",
"Asian person, maybe, near a mid-west location",
"Huntress follows in a state",
"Fight and give a thrashing to a tough character",
"Fire in a way through lack of energy",
"Indolence shown in a rite perhaps",
"Show sluggishness, i.e. Train sloppily",
"Babyhood as imagined",
"Delusory babyhood",
"In imagination, it's the beginning of life",
"A little child with a Spanish princess",
"Deduce there is no big blaze",
"Imply a small number will make a hell of a fire!",
"In Castro we see an unbeliever",
"Imparts knowledge in official documents",
"Singer's awful entrance",
"Occupy a building dressed like a monk",
"Receives what's left",
"What people who succeed do",
"Letter of introduction",
"Chums at home in a home, perhaps",
"Encroachments on the public highways?",
"Raids on raids, perhaps",
"He's in the right position not to be found out",
"He's in the right position not to be found out!",
"Able to be observed as perceptive enlightenment",
"Can be observed as a power of understanding",
"Perspicacity in one sense",
"Thorough knowledge can be seen",
"Visibility understanding",
"Having poor taste",
"Give hope by fashioable steeple",
"After the present month, everything to put in position for use",
"A second pressing",
"A term showing an alternative to being badly stained",
"Detains as substitute",
"Detains as substitute",
"Detached sun rail needing repair",
"Specifically used by diabetics",
"Concentrated as far as time in grammar is concerned",
"Concentrated on how the use of a verb may vary",
"Strained to define decimal point",
"You might find merit in the meantime",
"Confines one after another, we hear",
"I turned somehow to show what gate-crashers do",
"Useless, until changed inside that is",
"Red Ivan crosses the border aggressively",
"Discovers something new in airways",
"Discovers something new in airways?",
"Discovers something new in always?",
"Poetically upside down",
"The opposite of how the poet writes!",
"Bill's singing well",
"Country where anger is apparent",
"An Old Testament character, but he is confused with Islam",
"Cut off one as tardy as this",
"Set apart one as unpuncual as this",
"This strange sum recalled Panama, perhaps",
"Count each entry when one meets one in confusion",
"Make a detailed list",
"Quite miserable, but give a list of the particulars inside",
"A month before or after it, he takes care",
"Careless pedestians who get the bird! (3-7)",
"The French I hurt, but only in fun",
"Cry at wrong set being most enthusiastic",
"Sauce vessels raised",
"Steals the child while it sleeps",
"Relatively gentle colour?",
"Pink gin ordered for an important person (4-3)",
"Sort of critic who bangs on the door",
"Realising the ruler is around at present",
"Missing state given back to monarch",
"Brief description of the Spartans",
"Fidty snakes – and their game partners",
"Pull up near the convist – he may be caught loitering",
"Made redundant, so hedged one's bets",
"Put on canvas and displayed (4,3)",
"What air passengers are doing between one flight and another",
"A case for travelling light",
"Ten ran confusedly after fifty to the light",
"Clear another New York theft",
"Cowboy's equipment needed, as trail becomes confused",
"They're not oftem miscast in Westerns",
"Foreign sailors supplying the girl with a vehicle inside",
"Survive to the end of the innings?(4,3)",
"Dealers in suits?",
"Begin the dance, like an unrestricted puppy?(4,3)",
"Badly aligned at the front",
"Heroic aspirations were associated with his swimming",
"Many an employee is not a qualified driver",
"Pupil is level-headed and one who gets wages",
"Pupil is one who gets a pound in wages",
"Tethered to a building at the bottom of the field",
"Hide from the real chaos",
"Hide the real changes",
"Giving willingly",
"The position of the team given shelter? (3-4)",
"He gets what's left",
"A number, for example,finishes the inscriptions",
"One may be free to enjoy it",
"The garland is certain to provide relaxation",
"Allowed nine inside to go out, being easy-going",
"A boy's name or a girl's name",
"Its quartersw are hardly spotless",
"Son lies about injuries",
"Leave in the lurch – that's a disappointment (3-4)",
"Waives any penalty and discharges (4,3)",
"Leaves to dress for dinner",
"Serve cutlet with Eastern vegetable",
"Serve cutlet with Eastern vegetables",
"It was in form when young",
"It was in form when young",
"It was in form when young",
"Free translation of braille",
"Generous in providing a form of Braille",
"Authorise to break silence",
"Give authority to break silence",
"A sound defeat with the tongue",
"A shade less intense",
"Having lost weight, the girl looks different",
"One setting fire to the vessel",
"One setting fire to the vessel",
"The girl looks different, having slimmed",
"Not how a blow from a heavyweight can be taken?",
"Use the end of a spill to light the coal",
"City with its own memorial in Washington  DC",
"City with its own memorial in Washington DC",
"Faulty ruling at rugby",
"Ancestry leads to a row a long time afterwards",
"Ancestry reveals how old the dynasty is",
"Gin sling without topping or covering the insides",
"She is catty in a big way",
"Follows some cound advice",
"Follows some sound advice?",
"Showing an inclination for making an inventory",
"Cheer the proceedings with a vile pun, perhaps? (5,2)",
"Hated learner swearing at editor",
"Doesn't move quickly from Estoril",
"Beware of the sentry",
"Beware of the sentry(4-3)",
"The prospect for the watch",
"Regards the lot as O.K. Perhaps (5,2)",
"Makes a quick visit and watches the television programme (5,2)",
"Pays a quick visit and watches T.V. (5,2)",
"Obviously tights cannot be word thus",
"Most licentious, so stole without restraint",
"A draw is necessary before its winter emerges",
"Having the greatest volume",
"Inside information from the depths 3-4",
"Inside information near the bottom of the list?",
"In older transformation we will be let down",
"Cattle fodder found in Switzerland",
"Indian city needs good fortune at present",
"A match for the devil",
"Surely not one who loses his balance participating in moon project!",
"First-class backing for troubled reign in Africa",
"Teach me to twist the knife",
"Aim read out for wine production",
"Forced the terrorists to gather near Morocco",
"Dear ma and I produce wine",
"Great performer's at Rome",
"He can well perform some art composition",
"Most are out to get great musician",
"Famous battle colour",
"Got name of engine component mixed up",
"Mother's driving in fourth gear, and all at sea",
"Ruler to crack jokes in spring",
"How road buildersadvance? (4,3)",
"Slate me badly, being kind of cross",
"Handcuff Maclean somehow",
"Handcuff Maclean somehow",
"Coped with a fellow, advanced in years",
"Chap doesn't get any younger but still has control",
"Fellow with an appointment and a command",
"The fellow has a specified time for command to be carried out",
"Worker and when he'll get a commission",
"The male sort includes females as well",
"The male sort includes females as well",
"Ellis can provide this material",
"Etiquette for country houses, one hears",
"A three-legged race?",
"He takes steps to air his grievance in public",
"Spoils a trap inside the borders",
"Itinerant craftsman",
"Itinerant craftsman",
"Old salt miner near it can change drastically (7,7)",
"Returning gunners are shielded by the collier and the seaman",
"The things they're told are incredible",
"Wed an admirer, perhaps?",
"Arrange a star part in a wertern",
"Arrange a star part in a Western?",
"Warlike Roman poet",
"First woman found in this group of criminals",
"Swallow one cocktail",
"Red number obtainable back in the market",
"Caledonian taken in by mother's charms",
"Boy takes girl round stonework",
"Stonework produced by secret society?",
"A lump I have is substantial",
"Control may rest in the wrong position",
"Possibly the rest may control",
"Mother's pet dog?",
"Corresponds with what strikers use",
"Corresponds with what strikers use",
"Corresponds with what strikers use",
"Games played by strikers?",
"Officer over many a sailor",
"Sailor with the mate a great deal",
"Seaman with one friend and many more",
"I object to a certain action",
"The first person with a certain dimension",
"In a sense I'm breaking valuable crockery",
"Communication showing how old the muddle is",
"He meant to sort out a hazard to miners",
"The name used for march-gas",
"She may be thanked for sale delivery",
"She provides a personal delivery service!",
"Change of raiment for part of the mosque",
"For thirty seconds one has quiet at least",
"The least economical car mother goes after",
"I left the priest in church",
"I will leave the cleric for the abbey",
"Deceive with mad lies",
"Fail to get experience because the girl isn't at home",
"Made a false statement that the girl needs help",
"Spinter to charge embassy",
"Please, teacher, I have a letter",
"In manufacture it's wrong to make a slip",
"It's erroneous in manufacture!",
"We hear the girl employed is ill-treated",
"It's different in style for the dressmaker",
"Diffidence shown by a style with the pen",
"Does Tim upset the fashion designer?",
"Times do change for a lady of fashion",
"His cocktails are explosive",
"Not a subject put on in advance",
"Doctor to pull himself together in behaviour",
"Doctor firm about legendary bird in Africa",
"Hide in North Africa(7.7)",
"A thousand or less broken into pieces",
"Neckwear that will deaden the sound",
"Seating is never enough with such chairs",
"Wild horse has to dangle, as the cockney puts it.",
"It's hot to be in the lead in heavy going",
"Driving a point home",
"Pole is getting sick and it's catching",
"Pole is getting sick and it's catching",
"In town air. Obituary notices needed for 4",
"New native quarter shows simplicity",
"Girl eager to make cloth",
"Hastened up with speed to tell the tale",
"Sodium aroma coming into being",
"Not so pleasant – could be in tears",
"No artificial sign for the musician",
"Note not affected",
"As close as possible to Eastern arrangement",
"A decorative halter as it were",
"Noose that's collared!",
"Noose that's collared!",
"Noose?",
"Poverty led to being related",
"Disregard lack of care",
"Ten GLC members reassemble without a note of disregard",
"Not one nor the other counld be in there",
"He was thought to be the main controller",
"Writer returns by air or sea",
"Sodium aroma coming into being",
"Settling down among the birds?",
"Annoyed with stinging words?",
"Elementary particle no tuner can adjust",
"Elementary particle no tuner can adjust",
"Turn one into a particle without charge",
"In-lawed straight from the nest(3-4)",
"Modern entrance to old prison",
"Redistributive justice seems in disarray",
"Falls back again on the Royal Artillery",
"Falls for an artist bringing a profit back",
"I regain collection in Africa",
"I regain the country",
"Chemical container raised with speed",
"Metal put up by the price of the chemical",
"Certainly bound to be different (2,5)",
"Belts on the very best",
"Offensive rumour about a retired doctor",
"Offensive rumour about an up-and-coming doctor",
"Unpunctuated?",
"Perplex, but not in addition",
"The usual standards encompassing an early group of invaders",
"English city that could be rich now",
"Rum's not what the cure's made of",
"Rum's not what the cure's made of",
"Famous reason for being unable to dine at the restaurant",
"Impotent but distinguished",
"One who enjoys distinction without power",
"Signal lack of furniture",
"Duck spotted outside the hotel",
"Duck spotting outside the hotel",
"Revised section for advertisements",
"Section rearranged for advertisements",
"Beginners without bad habits?",
"Really good beginners",
"Present at present, but not in any place",
"With weapon raised, obtains valuable gold",
"Biblical book offers painkillers?",
"Possibly one rule man has broken",
"Possibly one rule man has broken",
"Community centre for retired ladies",
"A place of growing importance to gardeners",
"Children's room supplied by horticultural establishment",
"In which youngsters blossom forth",
"Lunatic needs hard cover.",
"Romans upset about a chap involved in rows",
"Stern-looking sportsmen",
"They have to exert some pull to make headway",
"Required by one who is doing porridge",
"Comment on what you see?",
"Make watchful remarks?",
"Make watchful remarks?",
"See you mention it!",
"Verbose sort of notice",
"Witness upset verbose characters",
"Regarded in Russia as revolutionary time of year",
"Get sea creature to work after a month",
"Oil cuts put eye-specialist out",
"Strange thing to say, occasionally",
"A part that can't be matched",
"Strange people get a letter concerning a scrap",
"Do so our fragrant results",
"Casual worker, not on duty",
"Aggressive action taken by those insulting",
"Crime of a receiver of stolen goods",
"Away with the worker – so casual!",
"One whose livelihood depends on commission?",
"Give plenty of lubrication to fuel source",
"Scrap an aged golf-club(3,4)",
"Scrap and aged golf-club (3,4)",
"Haing embarked, to receive meals",
"Looking out for a situation for the hands? (2,5)",
"Like Cyclops taking a singular view of life",
"A single person?",
"Oration composed in Canada",
"Oration in Canada",
"Oration in Canada",
"Oration re-written for part of Canada",
"Describing certain stone work on a track",
"Begin with a tune outside(4,3)",
"New opera in natural setting",
"It could be up to one to accelerate",
"New opera in a natural setting(4-3)",
"New opera in natural setting (4-3)",
"Opera in alfresco setting, maybe (4-3)",
"Declaim about exercise when cut up",
"Do remedial work in the theatre",
"Work in the theatre",
"Work with the man to ring up trouble for Shakespeare heroine",
"Is a poet affected by drugs?",
"What one thinks of love taking wing",
"He is against work on difficult problem...",
"Overburden the newspaper world with work",
"To treat cruelly,stop half the newspapers",
"No let up for the rich",
"They gave advice so wise and so clear, perhaps",
"A lengthy piece of spouting perhaps",
"Speech from Ontario",
"An alternative rota's rearranged for the speakers",
"One may hear it from a Liberal or a Conservative",
"One may hear it from a Socialist or a Conservative",
"Ten ran confusedly after fifty to the light",
"Alternative transactions will produce testing circumstances",
"Sea-lord orders trials",
"Regulated as instructed",
"This shows the sequence taken from a word in a lexicon",
"Flavouring mixture of orange with nothing added",
"Flavouring mixture of orange with nothing added",
"Fundamental shifting in cargo",
"Harps on about unfortunate children",
"Possibly sharp on children whose parents are late",
"...but torch is upsetting this one",
"Seat of empire",
"The result of not being in the company with me",
"Excel woth an alternative kind of sport",
"Exit in the open air?",
"Wolf backs out first in this issue",
"Briefly explain where the touch-judge may be seen",
"Briefly explain where the touch-judge may be seen",
"Survive, emerging full of power",
"Survive, emerging full of power",
"Not in the mail for remote station",
"Not in the mail for remote station",
"Remote station providing job in the open air?",
"It's a scandal, but not in the height of fashion!",
"Away team not having entered",
"Too big to have the 'in' vital statistics",
"Apparent, but not in a sister's concern",
"Apparent, but not in a sister's concern",
"Show too much enthusiasm in taking part",
"Show too much enthusiasm in taking part",
"To carve ham",
"Some crichet before tea, perhaps,in gorge",
"Have a supervisory job across the water",
"How a bishop will be in charge",
"In the box I'd a test-tube to create a chemical change",
"Aiming at appeasing the mightty sea",
"Boy and worker in spectacle",
"A good one will choose his coats carefully",
"Artist holds the boat",
"A row after a friend becomes a knight",
"Handy place for a painter to mix his colours",
"He'll expect you to show your hand",
"Came to the point perhaps",
"He hangs on the wall",
"Father uses syrop mixture for writing on!",
"Fatty in tatty garment is perfect specimen",
"A South Polar muddle, in short, surely superfluous in South Polar regions!",
"Father's enclosing tenancy payment for himself and mother!",
"Negotiates with real spy, maybe",
"Biased to some extent",
"Having a liking for the incomplete epithet",
"Incomplete description of one showing favouritism",
"Not just relating to some",
"Not wholly biased",
"Not wholly biased",
"Not wholly biased",
"Deep feetings for this kind of flower",
"The suffering of one coming in to die",
"Father's hours for recreation",
"I'm surrounded by artificial jewellery – it's a hobby",
"A girl after a bit of butter for her kneecap",
"Irishman joins uproar beying loyal to his country",
"An empty sort of settlement",
"Countryman is an industrious worker with vegetables",
"When about fifty, the lady is unequalled",
"Bird finds tin on untidy pile",
"Change in place for one with a big bill",
"Write to a friend how sentences are pronounced!",
"Article included among pennies as an act of contrition",
"For punishment, keep in and cane badly",
"Reading could give us unending pleasure (7,6)",
"With writers I have become thoughtful",
"They may be black or white pelts",
"Type of hairstyle for going inside to entertain",
"Type of hairstyle for going inside to entertainer",
"Carry on with more than one bad 7 (Answer to 7 was priest)",
"Priests get organised and keep trying",
"Relate to unusual painter",
"A bit of upper turbulence to cause agitation",
"Some skyscraper turbulence to disturb you",
"A fluctuation in foreign currency could be seen as steep",
"Tip up an unusually attractive plant",
"Selected about fifty to be preserved",
"Jame sold in jars",
"Painting old tribesman by river",
"Look at colour first, having conjunctivitis",
"Early worker puts one in column",
"Parties organised at sea",
"It will hold water for one about to set up camp",
"Vessel – lacking stabilisers",
"Hidden danger from mine subsidence",
"Mine collapse is a hazard",
"Appease a pal etc.",
"About the end of the flight, aircraft seen in the heavens",
"About the end of the flight, aircraft seen in the heavens",
"High-rise flat",
"Irresposible man about town or juvenile actor?",
"Quietly bound to be compliant",
"Promises to put a clue in the postscript",
"He plans to be a snooker-player about fifty",
"Does he get to the depths?",
"He gives an indication for a dog",
"He uses a gesture to indicate the dog",
"Place to be disturbed by fierce animal",
"Elizabeth the Second goes with splendour to ruined city",
"Support for bridge or some card game",
"Share harbour with one working",
"You have to do so",
"Cavity only a dope would fall into?",
"In which an old crock may come to grief?",
"Mixtures of drog particles",
"Mixtures of drug particles",
"They take shots at men at the wheel!",
"Action from the nurseryman and the billiards player",
"Exact summary by the first of the exponents",
"Forecast public relations on 20",
"This produces a novel introduction",
"Chatter about the Spanish high churchman",
"The first of the preachers to tell a story!",
"Peru led the revolution with a bit of music",
"Get ready before fruit is mentioned",
"A gift for the moment?",
"Contemporary gift",
"Contemporary gift",
"Current exhibit",
"Give now",
"Make an introduction here and now",
"Tense gift",
"Takes the chair, but not impartially",
"Continue with the ironing? (5,2)",
"Physical exercise gets reporters a rise?",
"Take for granted I object to purse being out",
"He makes the headlines",
"Playwright holds right part of computer",
"There are all types in his trade",
"Shocking threats cause disintegration",
"Rank of a military man undisclosed",
"This soldier can never appeasr in public",
"Or a part, perhaps, in proportion (3,4)",
"Go on! Take legal action",
"Not the result of division of labour!",
"Hold out a small pair on tender",
"Side view for the record",
"He foresees a hold-up over the reform",
"He foresees support before the reform",
"Support the confused forecaster",
"Support the wrong broadcaster",
"Support the wrong seer",
"Seek an engagement – or work, in plain language",
"Suggest a match, like the petty-officer in plain English",
"Objection raised in favour of trial",
"Potter's unreasonable objection",
"Professional examination will produce an objection",
"Establish I'd go in to furnish needs",
"Character on the bow shows great skill",
"Disease one itches strongly to have!",
"Make a book",
"Those who gamble on footballers",
"Accidents don't happen on this",
"Delayed, so returned to one's starting position(3,4)",
"Made a record of being subjugated (3,4)",
"A set of bedclothes",
"They took over from the night-shift",
"Put back the bar scraps for the pets",
"Frauds seen in court or in the press",
"Noisy game?",
"Broadcast a tirade, perhaps",
"Disreputable service comes with cod, perhaps",
"Gentleman burglar held to raise money for charity",
"Music for when the students' carnival takes place",
"When students have fun with popular music?",
"It is run on American lines (4-3)",
"Being abusive on a train?",
"It provides the guidelines for movement",
"The place where a toy train wails perhaps? (7,7)",
"The intention is to appear in town clothing",
"There's purpose in regular payment for clothes",
"Walker goes right up to marble figure",
"Wild worker on slope",
"The US stock market may depend on him",
"Hurried off to continue former 4 [CAPITAL]",
"Sprinted to make progress in Burma",
"Sprinted to make progress in Burma",
"Was the first to go after a row became embittered",
"Hit the drink when in state of empathy",
"Sympathetic relationship to strike with the left",
"Offering unseasoned timber is unfair treatment (4,3)",
"A recent reform put through again (2-5)",
"Pass Bill again (2-5)",
"About one who has a part for nuclear device",
"Nuclear plant concerning a thespian",
"Parson goes round a nuclear establishment",
"They refer to the books for universty men",
"Smoking jackets",
"Come to know how to make an encashment",
"Come to understand lies are awful",
"Understand about a variety of lies",
"The practical view is apparent in the kingdom",
"He has no fancy ideas about a catalogue",
"He has no illusions about an inclination",
"He is no dreamer about an inventory",
"In Montreal, it yields authenticity",
"Bringing up about a circle",
"Bounce back despite being tied up again",
"Once more obliged to make a come-back?",
"Recoil from being made confined again",
"Show resilience when tied down again",
"Raised after being razed",
"Goes back and surrenders again",
"Admit that you take in stolen goods?",
"Said to be named again in divorce proceedings",
"To do this to a lost soul could be a miracle",
"About different clues he keeps to himself",
"He remains aloof about unusual clues",
"They are pressed to entertain",
"Writes down unsurpassed acheivements",
"Reckon once more to tell the tale",
"Tell to add up the votes again",
"Put back the bedclothes and get better!",
"One of the addresses given by a cleric",
"It's diverting, though irrelevant (3,7)",
"Provide a new set of clothes as compensation",
"Top-coats required for those who furl the sails",
"Take some thought to provide a mirror image",
"Take some thought to provide a mirror image",
"Beneficial changes about school classes",
"It has no meaning",
"No answer",
"Raids on raids, perhaps",
"Uniform for a soldier",
"Pays attention to compliments",
"Fixed system of administration for nearly all the army unit",
"Even in peace he is prepared to fight",
"Serviceman ordered the usual?",
"Produce a publication again about children",
"Produce a publication again about children",
"Produce a second edition about children",
"Is resposive and becomes a member again",
"A return of ill-feeling",
"Go from bad to worse",
"Tension lost when half the barrel chopped",
"Free to hire again",
"Puts on another charge",
"What's left of the marines",
"Scrap and rave about men in disorder",
"Some err badly and show regret",
"Didn't stay put – drove me mad",
"Want to another house when ousted",
"Mends broken rapiers",
"Rips are put in order by mending",
"Carp and eel taken out? Put them back!",
"Substitute hard-wearing material with more delicate one",
"Let peer reform in full",
"News of gunfire",
"Lecture about trial impressions",
"Ask about a search",
"Ask politely about a search",
"About to be suspicious of the defence",
"Takes umbridge when told to go in the reserves",
"1 to lay up",
"A set-back about lyrical writing",
"Book store?",
"Go back again for publicity in 14 (adverse)",
"Save up to get engaged",
"Desires to change lives",
"Gives in notice, but endorses contract again",
"Decide to separate the component partsd",
"Gives a new classification to holiday locations",
"About unbroken echo",
"Echo again in good condition",
"What a sceptre should make one show?",
"More than one summary continues after a break",
"Starts working again on summaries",
"Possibly re-unite a train",
"Go back round the terrace",
"Again negociate a withdrawal",
"The only thing a defeated army can beat",
"Withdraw to negotiate again",
"Shows several changes",
"Shows several changes",
"Get even with Reg., perhaps?",
"Retaliation concerning archdeacon, for example, on way back",
"Be sorry about unrising income",
"Regret being about to level out income",
"Adore one included in daydream",
"Again, poetry is the opposite",
"Go back about poetry",
"One goes into it backwards",
"Wickedness in the anarchist is assailed with abuse",
"It brings new life to a drama, for example",
"Do they accrue from conflict among anachists?",
"End the telephone conversation as sign of broken engagement? (4,3)",
"There's nothing in 15 becoming crazy about repartee",
"Its root goes into a rice dish",
"I arrive upset in a holiday spot",
"Nice coastal environment",
"Somehow I arrive in continental holiday area",
"He's on the way to work",
"Our grey concoction is a bit of knavishness",
"Revel spoiled by rioters",
"Waves – or wave makers",
"An account that has been overdrawn?",
"Tell a fanciful tale from Cremona",
"The founder of Rome made our slum",
"Where sharpers might put nest-eggs",
"Some kangaroos terrify a bird",
"Favour nothing in street demolition",
"To steer as a favour",
"Turns round to stare in a way",
"Rake money in, in the usual way",
"They creat a disturbance, but the noise fades away",
"Trouble-makers seen when quarrels are about to fade away",
"Stern directors",
"Exhausted by overwork – make disparaging remarks (3,4)",
"In poor health – result of a car accident (3,4)",
"The opposite of praise? Well, not! (3,4)",
"Disturbance in court, perhaps",
"In a hurry to get elected?",
"Is it for the fleet footed",
"He obviously featured in a U.S.S.R. Re-shuffle",
"Like the troops who were in a U.S.S.R. Formation",
"...and corrosion is surrounding the same number of peasants",
"Takes stock and amemnds the results",
"Takes stock and falsifies the results",
"Dismal studies make one blue",
"Dad's set out to be most unhappy",
"Their actions may be painfully apparent to others",
"Hunting expeditions created a fair disturbance in the ship",
"A boy in error becomes a Muslim leader",
"Learns about love in Italy",
"New Orleans is in Italy!",
"Entails being outstanding",
"Entails being radical and striking",
"Entails being radical and striking",
"Entails prominent reformer",
"Prominent foreigner appearing in the street",
"Prominent foreigner in the way",
"Prominent visitor from abroad seen in the street",
"Prominent visitor from abroad seen in the street",
"In disorganised side everybody went forward to attack",
"A realist could make you cross",
"Some of the stockings and also footwear",
"A race between two Poles and an Arab",
"Sired an unreliable swimmer",
"Sired an unreliable swimmer",
"An act is horribly diabolical",
"Schoolboy's book case",
"Leave nothing to be desired",
"Provide enough to convince",
"Interviwed 1,000 taken sick at timberworks(3-4)",
"Ties the rest in knots",
"Red castle rebuilt right in the middle",
"Frightens about five in mufflers",
"He has doubts about being poisoned when swallowing concoction first",
"It is noted for vigorous playing",
"In which one experiments with scenic arrangement before the end of the movie",
"Skill taught in laboritories",
"Cut, and is cross perhaps",
"Company in America turned colour when scrubbed",
"Did a rough job of cleaning",
"Played the fiddle and got a bare living",
"A poor fiddler outside the door",
"Withdraw to ease irritation",
"You're not handicapped with such a slight injury",
"You're not handicapped with such a slight injury",
"A hundred cheers perhaps or one cry of terror",
"This owl doesn't give a hoot",
"This owl doesn't give a hoot",
"Shows films behind which one may hide",
"Not original writers",
"Drink can make us cry, perhaps, about politician",
"Concientious objection",
"Hesitate on moral grounds – to prescribe twenty grains?",
"A runaway affair on ship",
"Deliberately sink coal vessel",
"Cuts down visibility on the main routes(3,4)",
"Ale laws as defence against the advance of water (3-4)",
"A single way of making an impression",
"The main fish for hunting aquatic creatures",
"I see ads, diverted to holiday area",
"Adds some savour to certain times",
"Main plant source of iodine",
"Private point to hide",
"Hide in the South-Eastern part of a Mediterranean isle",
"Hide is unknown to a point",
"Hide is unknown to a point",
"Private point to hide",
"Notices for this department",
"Distraint is enough to produce a stroke",
"It's not altruistic to market sea-food, we hear",
"Remains in special study group",
"Law-maker gives foreign coin a rise",
"List moved up to Japanese coin by law maker",
"One-star politician?",
"Transmitting a different sign about the finale",
"Wildly she raps celestial beings",
"Addresses given by clerks in the services",
"A parliamentary term?",
"Meeting that has no standing",
"Position defender so as to hinder advance (3,4)",
"The good weather will continue, and the scenery's not bad (3,4)",
"Prepared scheme – for winning a tennis match? (3,4)",
"Prepared scheme – for winning a tennis match? (3,4)",
"Determined to attack",
"Locked spine produces a relapse (3-4)",
"Seats one pays for",
"He pays up and stays",
"He pays up and stays",
"Pays and stays",
"Pays for lights",
"Reveals quite a number in disorder",
"Harsh Dutch leader is cut off",
"Justice in Shakespeare is far from profound",
"Is this what the mathemsatician is using dividers for?",
"Threats to smash",
"Badly adheres to cut",
"He reads the cut version",
"Feels the effect of southern winters in France",
"Quiet! Woman is out to get exhibitionist!",
"Piercing calls from a hiker put on board",
"Puts one in prison and never says a word(5,2)",
"Weaver's instrument may go into space!",
"Vehicle taken by team is usually attached to a motor-cycle",
"They provide information at the track-side",
"Lady soaring?",
"License absence of noise",
"Genuine because half-real",
"Distinguished feature of later as opposed to latter vest",
"One letter needed for undergarment",
"Top run at the West End",
"Vice emperor on the decline",
"Pins inserted into joints",
"He may toss at sea or at the cricket ground",
"It's usually kept by the hearth or sink",
"Using an extinguisher and quenching one's thirst",
"Could be the top men in the building trade",
"Some trickery doesn't amount to much, we hear",
"The scale associated with the trombonist!",
"Footwear for one on ice?",
"Mule not firm-footed, presumably",
"Having the smallest rate",
"Strange arm-rest could become more fashionable",
"Showed a sign of cold and contempt?",
"Thus a monarch becomes thoroughly wet",
"Red soil suited to army man",
"Thus, being lawful, make an appeal",
"He drew wisdom from the sun and, oddly enough, the moon",
"Nobody in particular",
"Nobody in particular",
"Undistinguished character",
"A highly vocal female",
"She gets the highest score for her performance",
"Upset parson with love for a singer",
"More reliable plumber",
"Dog in lapse",
"A help or a hindrance in the works",
"Distinctive one in different places",
"Particular place is reorganised",
"This place is out of the ordinary",
"A group that is seen in abbreviated spectacles",
"It may appear to frighten people",
"Incidental result of drive being cancelled",
"The continual rounds of wage increases?",
"Drinks lacking body?",
"They may, of course, be raised in glasses",
"Spread out when shown little Diana missing",
"Given marks for having been observant",
"Picked out as blotchy",
"Trap cuts the spaniel's tail off",
"They reduce the shock from jumps",
"Grows vegetables",
"Shoots something to eat",
"Evened the score by bribery",
"Framework for putting on a play?",
"Instead of becoming blemished",
"Attitudes drivers may take of course",
"Peremptory demand for a rise (5,2)",
"Almost the statue of a substitute",
"Device for fastening loose plaster!",
"What an acting astronomer might aspire to?",
"Peering at articles wrapped round with cord",
"Race movement begins under his order",
"Somehow let rats return to cause alarm",
"Saying money is put into kind of party for men",
"The last form of secrecy",
"In which cooking may be done at sea",
"It may need a jack up before being repaired",
"A master-copy for various clients",
"Clients provide pattern for duplication",
"Duplicating material provided by clients",
"Gets relations by marriage to feel one's feet?",
"Tries to change the French, being destitute of ideas",
"Show more resolve and adopt a formal position",
"ompous description of high-steppers",
"ompous description of high-steppers",
"One liking to cause trouble in the kitchen",
"It's important to one's standing as a rider",
"What the rider needs to boot",
"But the dentist went on working when he did this",
"Price paid for stocking?",
"So great a redistribution in warehousing",
"What one pays for stocking",
"Relations of southern politicians",
"Tales of southern politicians",
"Hardships affect artists",
"Leaves high and dry on the beaches",
"Remained about right but wandered off",
"Bacon's lines",
"Exercise done by a prisoner",
"Extend a sentence",
"Extend period of imprisonment",
"Takes good steps not to have to walk in the streets",
"Takes good steps not to have to walk in the streets",
"Does one hit one not working",
"They reward or punish unruly priests",
"Soothes after lashes?",
"Soothes after lashes?",
"Makes slow progress by street-car",
"Makes slow progress by street-car",
"Knob with ten possibilities given to pupil",
"Scholar of French in a spectacular trick",
"Scholar who might be stunted",
"Possibly it's used in lessons",
"Scrutinises pieces used in music lessons",
"Performed an antic that;s understood",
"It's grand picking up bus by tree",
"It's heavenly under a tree",
"One's own dispatch is brought about by this",
"Precis dealt with on the spot",
"Precis dealt with on the spot",
"Tops two thousand in legal actions",
"Outer garment for the knight, by the sound of it",
"What the star at water-sport might skim",
"Boy about to press for the operator",
"Doctor has a bonelessfish",
"By which the knight is designated, one hears",
"By which the knight is designated, one teams",
"He may be guilty in thought if not in deed",
"Support us in shame",
"Support us in shame",
"Law is revised about greeting people in Africa",
"The language of his wail",
"Free from bitterness",
"Furniture item used for an upper class work of art",
"Taking another course in sewing",
"Swimmer who may develop into a jumper",
"Assumes the responsibility to adopt the boy",
"Proceeds, thanks to royalty",
"Returns from business",
"Thanks rulers for receipts",
"Slecial gifts of money",
"The money certain people used to have for gifts",
"City in great trouble",
"After tea drank a mixture – contained in this?",
"Brown, the strange dark drinking vessel",
"A sudden fit of rage when the brown-shirt has a drink",
"Came to a dine end",
"They give the prices of food taxes",
"Spoil the sailor with a broken shin",
"One sailor followed by others – they're formidable types",
"More seasoned type of artiste",
"Stir tea – it could be more palatable",
"Gossips triflingly and produces stoties about an abstainer",
"Take ace cook for often-toasted bun.",
"When the char arrives",
"A live TV broadcast in Israel(3,4)",
"Catch up, being capable of being held on to",
"It's reasonavle to have 10 who are clever",
"They pay the rent for a number of busy workers",
"Turks initially embrace twice five times",
"Intones uusual strain",
"Note sin to strain",
"One isn't put out by it, but it's a strain",
"Carter trip East cause row",
"Upset a caterer in a domestic row",
"The dog to go astray in a row",
"Took food after examination, having made a will",
"A tent collapsing by American causes disease",
"Ties the rest in knots",
"Ties the rest in knots",
"Words on the river surface",
"Where play  and work mean the same thing?",
"Where, at playtime, he is involved in an unusual treat",
"This can be proved by thoser people holding raw material",
"Possibly pray when under the treatment",
"Possibly pray when under the treatment",
"Pray the change will do you good!",
"They are about to knock medical treatment",
"They have to knock inside for treatment",
"They knock inside for treatment",
"Inside it is what the rider uses for control",
"She puts heaters out",
"Minotaur-killer brought the things here to us",
"It enables one to have protection at one's fingertips",
"Metal cover protects the sewer",
"Metal cover protects the sewer",
"One who gets the needle should keep it on hand",
"Ant-bite upsets the foreigner",
"Bills of fare?",
"A catty female",
"Catty female",
"Lorries wrecked by pig-headed",
"I am included in exchanges of indective",
"One in exchanges of streams of invective",
"Giant I beat in less than a moment",
"Two small birds make one",
"Two small birds make one",
"They are flattering to a side, maybe",
"There's not smoke without it",
"Workers from Estoril",
"This is not just an obstruction to bell-ringers, by the way",
"Mouth-organs",
"Mouth-organs?",
"Present-day conclusion?",
"Anne got the weight wrtong",
"No agent will change the weight",
"Dated and removed (4,3)",
"The art of shaping the box, for instance",
"Not a rod used for a heavy blow",
"Possibly it's too darn awkward for most sailors!",
"Rent fuss produces a disastrous blow",
"Electric ray could sink a ship",
"Naval weapon or depot perhaps",
"Hill gets split by the stream",
"Hill spilt by flood",
"The strain caused by doing the twist",
"To agree completely",
"Feel happy to gloss over",
"Feel happy to gloss over (5,2)",
"Persuaded to give donation, being emotionally affected",
"What's the excursionist doing getting involved in a gun riot?",
"Area of land or what is needed to cultivate it?",
"Run down rude act",
"Such lights are on all day",
"Grew old in the attempt – a disaster!",
"Old people in attempt to produce sad play",
"A coach who makes many coaches show hesitation",
"The horse wouldn't be prepared to run without him",
"Star in passage",
"Travelling goods will be in it",
"Bar in the air demanding acrobatic manoeuvres",
"Hard labour getting Virginia in the track",
"Electra produced something thick and sweet",
"Let care be used in preparing sticky sweetener",
"Altered pedal",
"Machine attachment requiring skilful footwork",
"More than grounds for great disloyalty",
"One star turn nobody applauds",
"State crime that ruins the senator",
"Stood, a drink by the doctor?",
"A lot more complicated musical effect",
"A lot more complicated musical effect",
"How to sing a piece written in quavers?",
"A supporter of the board disconcerts the settler",
"Variety of letters providing support for the board",
"Fool the French on the run",
"Fool the French on the run",
"Makes sure gear measures up to personal specifications (5,2)",
"Time-server in better order",
"Small article produced by an erratic knitter",
"Excursion to get foeign oil ib North Aftica",
"Oil change needed after excursion to North African location",
"Stumble on crude oil in N. Africa",
"Accident prone tourist",
"Accident-prone tourist?",
"Runs lightly onto the scene and stumbles! (5,2)",
"Four in court proceedins of little importance",
"Four involved in court case, but it's not importasnt",
"Four make an appearance in a trial of no importance",
"Insignificant test about four",
"The soldier puts nothing in the report that's sent back",
"Hot areas put right in subjects to be discussed",
"Difficulty of initially taking Russian money",
"Problems for Russian currency after Thursday's rise initially",
"Skiving from school makes aunt cry",
"He cares for others",
"He cares for others",
"He cares for others",
"Female Russian artisan, perhaps",
"Melodious fun with lute, in a way!",
"Musical fun with a lute perhaps",
"A unit is ordered to somewhere in N. Africa",
"In a suit designed for a hot country",
"Commotion caused by our Tim with fifty more",
"Woolly couple(4-3)",
"A tortuous swindler",
"Does he dishonestly turn the screws on?",
"Most woe-begotten pair",
"Greek hero, odly sly in custome",
"Countless given by posh politician – of youngish age?",
"The sort of combat in which one id not 'urt",
"Take the lid off something?",
"Makes straight for it",
"Take off topless bikini",
"Take off topless bikini!",
"Not touched by consumption, perhaps",
"It will be a poor match with such contestants",
"Unseat one with a rush, perhaps",
"Fabulous supporter of royalty",
"All the same, it suits some people",
"In which we serve",
"It's even assumed by the soldier",
"Met punk rocker looking slovenly",
"Puts in charge? Quite the opposite",
"Liberate one soul in torment",
"16 roughly is about right to weaken resolve",
"Disentangle one French composer",
"Sort out the middle of a tune with the composer",
"Under it changes are yet to be made",
"Under it changes are yet to be made",
"Under it changes are yet to be made",
"Funicular to London",
"Results of lobbing?",
"Parvenu is out of bed to begin with",
"Don't expend so much – it's futile",
"Don't expend so much – it's futile",
"It's futile to employ a smaller number",
"To economise is of no avail",
"Unavailing suggestion for economy",
"They take great interest in your need for cash",
"Made a pretence a reality?",
"It may serve to let us in perhaps",
"Inject a cubic centimetre into a climber as a safeguard",
"Inject a cubic-centimetre into a climbing plant as a safeguard",
"Painter who might be collared",
"Painter who might be collared",
"The flavour of everything sent back on the first vehicle",
"Polish runs in to disappear",
"Arched and jumped",
"..with open gallery and girl outside.",
"Clergyman returns with crushed bean and flower",
"There's a lot to be said for being so",
"In case this is the decision",
"Is the parson shortly back on form?",
"It's wicked for 6 to have 100 debts",
"They hold slides and look at them",
"I will be encircled by conceited rogue",
"The rogue gets in beneath the house",
"The rogueis at home under the house",
"The knave is sick in vain",
"Abuse musical instrument, brewing tea on it",
"Faces six wise men",
"Dreams there's nothing in six transgressions",
"Is it after five or later he calls?",
"Is it after five or later he calls?",
"Its meals are usually late",
"Its meals are usually late",
"Fighting a long way into merchanise",
"The western stream turns out to be the hottest",
"Cry about donkey at a festive occasion",
"Loss of a theatrical fixture after the end of the show",
"Walter's still a good-for-nothing though reformed",
"Why a let-out for rich people",
"Why late reform made rich?",
"Bides one's time, we hear, with heavy measures",
"From the occident, youy and I appear forbidding",
"Now that can be made into a piece of furniture",
"The sort of strike that produces violent uncontrolled act (4-3)",
"Tigerish blows to continuity in industrial output (4-3,7)",
"Making bequests without reluctance",
"You mat lose all by being charming",
"Deeply respect the magistrate",
"Shocking rows before Edward is beaten",
"The least successful journalist's yarn",
"They're shadows of their formere selves",
"Tributes to the dead from the wars",
"Tributes to the dead from the wars",
"This is a good tip for a crease in the skin",
"Surrounded by summonses he performs contortions",
"Penned legal documents to 10",
"It's overlooked by some Muslim women",
"Longed to have deanery rebuilt",
"Female Russian artisan in trouble",
"I hear you will record the making of this cake (4,3)",
"A blazer put on at Christmas time (4-3)"



);
ANSWER= new Array(
"ABANDON",
"ABANDON",
"ABANDON",
"ABETTOR",
"ABETTOR",
"ABIGAIL",
"ABILITY",
"ABJURED",
"ABRIDGE",
"ABRIDGE",
"ABRIDGE",
"ABRIDGE",
"ABRIDGE",
"ABSOLVE",
"ABSTAIN",
"ABSTAIN",
"ACCEPTS",
"ACCOUNT",
"ACCUSER",
"ACCUSER",
"ACCUSER",
"ACOLYTE",
"ACQUIRE",
"ACQUITS",
"ACREAGE",
"ACREAGE",
"ACROBAT",
"ACTRESS",
"ACTRESS",
"ACTRESS",
"ADDRESS",
"ADDRESS",
"ADDRESS",
"ADDRESS",
"ADHERED",
"ADHERES",
"ADMIRAL",
"ADMIRER",
"ADVANCE",
"ADVANCE",
"ADVERSE",
"ADVICES",
"AGAINST",
"AGELESS",
"AGITATE",
"AGONIES",
"AGONIES",
"AGROUND",
"AGROUND",
"AGROUND",
"AILMENT",
"AIR ACES",
"AIR-RAID SHELTER",
"AIRLESS",
"AIRLIFT",
"AIRWAYS",
"ALERTED",
"ALGEBRA",
"ALI BABA",
"ALIGHTS",
"ALIGNED",
"ALLEGRO",
"ALLOWED",
"ALLOWED",
"ALLOWED",
"ALMONER",
"ALMONER",
"AMASSES",
"AMATEUR",
"AMERICA",
"AMIABLE",
"AMIABLE",
"AMIABLE",
"AMIABLE",
"AMNESIA",
"AMNESIA",
"AMNESIA",
"AMUSING",
"ANAEMIA",
"ANAEMIA",
"ANAGRAM",
"ANAGRAM",
"ANALYST",
"ANALYST",
"ANARCHY",
"ANATOMY",
"ANCIENT",
"ANDANTE",
"ANDORA",
"ANEMONE",
"ANEMONE",
"ANGERED",
"ANGERED",
"ANGLERS",
"ANGULAR",
"ANIMATE",
"ANIMATE",
"ANISEED",
"ANNOYED",
"ANNUITY",
"ANSWERS",
"ANT-HILL",
"ANTIGUA",
"ANTONIO",
"ANYBODY",
"ANYBODY",
"ANYTIME",
"APOSTLE",
"APOSTLE",
"APPAREL",
"APPAREL",
"APPEASE",
"APPLIES",
"APPOINT",
"APPOINT",
"APRICOT",
"AQUATIC",
"ARC-LAMP",
"ARCHAIC",
"ARCHERY",
"ARCHERY",
"ARCHING",
"ARCHWAY",
"ARDUOUS",
"ARMENIA",
"AROUSED",
"ARRANGE",
"ARRANGE",
"ARRANGE",
"ARRESTS",
"ARSENAL",
"ARSENIC",
"ARTICLE",
"ARTISAN",
"ARTISAN",
"ARTISAN",
"ARTISTE",
"ARTISTE",
"ASCETIC",
"ASH-TRAY",
"ASHIVER",
"ASININE",
"ASPIRIN",
"ASPIRIN",
"ASPIRIN",
"ASSAULT",
"ASSAULT",
"ASSENTS",
"ASSERTS",
"ASSISTS",
"ASSUAGE",
"ASSUMES",
"ASSUMES",
"ASSUMES",
"ASTOUND",
"ASUNDER",
"AT A COST",
"AT STAKE",
"ATHEIST",
"ATHLETE",
"ATHLETE",
"ATHLETE",
"ATTENDS",
"ATTENDS",
"ATTENDS",
"AUCTION",
"AUCTION",
"AUDITOR",
"AUDITOR",
"AUDITOR",
"AUNTIES",
"AUSTERE",
"AUSTERE",
"AUTOBUS",
"AVAILED",
"AVARICE",
"AVARICE",
"AVARICE",
"AVARICE",
"AVERAGE",
"AVERAGE",
"AVERAGE",
"AVERAGE",
"AVERAGE",
"AVERAGE",
"AVERTED",
"BABYLON",
"BABYLON",
"BACK OUT",
"BACKERS",
"BALANCE",
"BALANCE",
"BALL BOY",
"BAND SAW",
"BANNERS",
"BAPTIST",
"BARGAIN",
"BARMAID",
"BARRAGE",
"BASTION",
"BASTION",
"BEARING",
"BEDROOM",
"BEDROOM",
"BELGIAN",
"BELIEVE",
"BELLOWS",
"BELLOWS",
"BELLOWS",
"BEMUSED",
"BENEFIT",
"BENEFIT",
"BENISON",
"BERATED",
"BINDING",
"BLEATED",
"BLOOMER",
"BLOOMER",
"BLOOMER",
"BOARDER",
"BOARDER",
"BOLSTER",
"BOOKISH",
"BOOKISH",
"BOREDOM",
"BOREDOM",
"BOREDOM",
"BORROWS",
"BOUNDED",
"BOX-TREE",
"BRAGGED",
"BRAN TUB",
"BRANDED",
"BRASSIE",
"BREADTH",
"BREAK UP",
"BREAKER",
"BRIGADE",
"BRIGAND",
"BRISTLE",
"BRITTLE",
"BROCADE",
"BROTHER",
"BROUGHT",
"BUILDER",
"CABARET",
"CABARET",
"CAHOOTS",
"CALIBRE",
"CALL FOR",
"CALL OUT",
"CALL-BOY",
"CALLING",
"CALLOUS",
"CALLS ON",
"CAMELOT",
"CANDIDA",
"CANNERY",
"CANNONS",
"CAPITAL",
"CAPITAL",
"CAPITAL",
"CAPITAL",
"CARAMEL",
"CARAVAN",
"CARBINE",
"CARRIED",
"CARTONS",
"CARTOON",
"CAST OFF",
"CAST OUT",
"CASTLED",
"CATARRH",
"CATERER",
"CATS-EYE",
"CAUTION",
"CENSURE",
"CENTAUR",
"CERTAIN",
"CHAGRIN",
"CHAIRED",
"CHANGES",
"CHANGES",
"CHANTER",
"CHAPLIN",
"CHAPTER",
"CHARGER",
"CHARGES",
"CHARMED",
"CHEERIO",
"CHEETAH",
"CHIANTI",
"CHICAGO",
"CHIME IN",
"CHIMERA",
"CISTERN",
"CITADEL",
"CITADEL",
"CLAMOUR",
"CLAMOUR",
"CLAMOUR",
"CLASSED",
"CLASSES",
"CLAUSES",
"CLEANER",
"CLEANER",
"CLEARED",
"CLEARLY",
"CLEAVER",
"CLIMBER",
"CLIQUES",
"CLOSING",
"CLOTHES",
"CLOTHES",
"CLOVERS",
"CLUBBED",
"COFFERS",
"COLLECT",
"COLLIER",
"COLLIER",
"COMPACT",
"COMPASS",
"COMPASS",
"COMPERE",
"COMPERE",
"CONCEAL",
"CONCERN",
"CONCERN",
"CONCERN",
"CONCERT",
"CONCORD",
"CONCORD",
"CONDUCT",
"CONDUCT",
"CONFORM",
"CONSOLE",
"CONSORT",
"CONTACT",
"CONTACT",
"CONTAIN",
"CONTEND",
"CONTENT",
"CONTENT",
"CONTEST",
"CONTEST",
"CONTEST",
"CONTOUR",
"CONTOUR",
"CONTOUR",
"CONTOUR",
"CONVENT",
"COOLERS",
"COPPERS",
"CORACLE",
"CORINTH",
"CORONER",
"CORSAIR",
"CORTEGE",
"COSTUME",
"COSTUME",
"COUNTER",
"COUNTRY-DANCING",
"COUPLET",
"COUPLET",
"COURSER",
"COVERED",
"COVERED",
"COWERED",
"COWHERD",
"COWHERD",
"CRASHES",
"CREATES",
"CREATES",
"CREATES",
"CREATOR",
"CREEPER",
"CREEPER",
"CREEPER",
"CREEPER",
"CRICKET",
"CRICKET",
"CRIMSON",
"CRIMSON",
"CROOKED",
"CROPPER",
"CROPPER",
"CROPPER",
"CROSSED",
"CROSSES",
"CROWING",
"CROWING",
"CRUMBLE",
"CRYSTAL",
"CURABLE",
"CURATOR",
"CURRANT",
"CURRENT",
"CURTAIL",
"CURTAIN",
"CURTAIN",
"CUTTING",
"CYANIDE",
"CYCLONE",
"DALLIES",
"DARLING",
"DASHING",
"DEAD-END",
"DEAD-END",
"DEAD-PAN",
"DEAREST",
"DEAREST",
"DEBASED",
"DECAMPS",
"DECIDER",
"DECIDER",
"DECIMAL",
"DECLAIM",
"DECLARE",
"DECLINE",
"DECLINE",
"DECLINE",
"DECLINE",
"DECLINE",
"DECORUM",
"DELAYED",
"DELETED",
"DEMERIT",
"DENTIST",
"DENTIST",
"DENTURE",
"DEPUTED",
"DERVISH",
"DERWENT",
"DESCANT",
"DESCENT",
"DESERTS",
"DESERTS",
"DESERVE",
"DESIGNS",
"DESIGNS",
"DESIGNS",
"DESIGNS",
"DESPAIR",
"DESPAIR",
"DESPAIR",
"DESSERT",
"DESSERTS",
"DETROIT",
"DETROIT",
"DIALECT",
"DIALLED",
"DICKENS",
"DICTATE",
"DIE-HARD",
"DIES OUT",
"DIFFUSE",
"DIGNITY",
"DIMPLES",
"DISCERN",
"DISCERN",
"DISCUSS",
"DISDAIN",
"DISDAIN",
"DISLIKE",
"DISLIKE",
"DISPLAY",
"DISPLAY",
"DISPLAY",
"DISPOSE",
"DISPOSE",
"DISPUTE",
"DISSENT",
"DISTAFF",
"DITTIES",
"DIVERSE",
"DIVERSE",
"DOG-STAR",
"DOLORES",
"DONKEYS",
"DORMANT",
"DORMANT",
"DRAGOON",
"DRAGOON",
"DRAPERS",
"DRAUGHT",
"DRAW OUT",
"DRESDEN",
"DRESS UP",
"DRESSER",
"DRESSES",
"DRESSES",
"DRINKER",
"DRIVING",
"DROPPED",
"DRY DOCK",
"DUNGEON",
"DURABLE",
"DUST_PAN",
"EAR-DRUM",
"EARACHE",
"EARLDOM",
"EARNEST",
"EARNEST",
"EARNING",
"EARRING",
"EARSHOT",
"EARTHED",
"EARTHED",
"EASTERN",
"EASTERN",
"EASTERN",
"EBB-TIDE",
"ECLIPSE",
"ECSTASY",
"EDDYING",
"EDITION",
"EDITORS",
"EFFORTS",
"EGG FLIP",
"EGOTISM",
"EIGHTS",
"EJECTED",
"ELAPSES",
"ELAPSES",
"ELASTIC",
"ELASTIC",
"ELASTIC",
"ELASTIC",
"ELASTIC",
"ELATION",
"ELATION",
"ELATION",
"ELEANOR",
"ELECTOR",
"ELECTOR",
"ELECTOR",
"ELECTOR",
"ELECTOR",
"ELEMENT",
"ELEMENT",
"ELEMENT",
"ELUSIVE",
"EMBARGO",
"EMBARGO",
"EMBARGO",
"EMBARGO",
"EMBRACE",
"EMBRACE",
"EMBRACE",
"EMBRACE",
"EMOTION",
"EMOTION",
"EMOTION",
"EMOTION",
"EMOTIVE",
"EMPOWER",
"EMPOWER",
"EMPOWER",
"EMULATE",
"ENABLES",
"ENAMOUR",
"ENCHAIN",
"ENCHANT",
"ENCHANT",
"END-GAME",
"ENDLESS",
"ENDLESS",
"ENDLESS",
"ENDORSE",
"ENDOWED",
"ENDURED",
"ENDURER",
"ENDURES",
"ENDURES",
"ENFOLDS",
"ENGAGED",
"ENJOYED",
"ENLARGE",
"ENLARGE",
"ENLARGE",
"ENSIGNS",
"ENSIGNS",
"ENSURED",
"ENTITLE",
"ENTITLE",
"ENTRANT",
"ENTRANT",
"ENTREAT",
"ENTRIES",
"ENVIOUS",
"EPICURE",
"EPICURE",
"EPISTLE",
"EPISTLE",
"EPISTLE",
"EPITAPH",
"EPITAPH",
"EPITHET",
"EROSION",
"EROSION",
"ERRATIC",
"ESCAPED",
"ESPARTO",
"ESTATES",
"ETERNAL",
"EVACUEE",
"EVASION",
"EVASIVE",
"EVASURE",
"EVENING SERVICE",
"EVENS UP",
"EVEREST",
"EVEREST",
"EVEREST",
"EWE-LAMB",
"EXACTOR",
"EXAMPLE",
"EXAMPLE",
"EXCERPT",
"EXHAUST",
"EXHAUST",
"EXPENSE",
"EXPENSE",
"EXPLAIN",
"EXPORTS",
"EXPOSAL",
"EXPOSED",
"EXPRESS",
"EXTRACT",
"EXTREME",
"EXTREME",
"EXTREME",
"EXTREME",
"EXTREME",
"EYE OPEN",
"EYE-WASH",
"EYELESS",
"EYELESS",
"EYELETS",
"EYESORE",
"EYEWASH",
"FACTION",
"FACTION",
"FAILING",
"FAIRWAY",
"FAIRWAY",
"FAIRWAY",
"FAIRWAY",
"FAIRWAY",
"FALL OUT",
"FALSITY",
"FARRPWS",
"FARTHER",
"FEATHER",
"FEBRILE",
"FENCING",
"FENCING",
"FERVENT",
"FICTION",
"FICTION",
"FIDDLER",
"FIDDLER",
"FILMING",
"FIREMAN",
"FITTEST",
"FLAG-DAY",
"FLAGGED",
"FLAMING",
"FLATTER",
"FLEDGES",
"FLIGHTY",
"FLOWING",
"FONDLES",
"FOOD FOR THOUGHT",
"FOOLERY",
"FORAGED",
"FORAGES",
"FORBEAR",
"FOREIGN",
"FOREMAN",
"FORESTS",
"FORFEIT",
"FORGERY",
"FORGERY",
"FORTUNE",
"FOUNDER",
"FRAGILE",
"FREEDOM",
"FREEDOM",
"FREEDOM",
"FREIGHT",
"FRIENDS",
"FRIENDS",
"FRIGATE",
"FRITTER",
"FRITTER",
"FUNERAL ORATION",
"FUNFAIR",
"FUNFAIR",
"FURNISH",
"GALLEON",
"GALLEON",
"GALLERY",
"GAMBLER",
"GAMBLER",
"GARBAGE",
"GARNETS",
"GARNETS",
"GAS-MASK",
"GATEWAY",
"GATHERS",
"GENERAL",
"GENERAL",
"GENERAL",
"GENERAL",
"GENERAL",
"GENERAL",
"GENERAL MEETING",
"GENESIS",
"GENTEEL",
"GENTEEL",
"GENUINE",
"GESTAPO",
"GESTAPO",
"GET AWAY",
"GET AWAY",
"GETAWAY",
"GEYSERS",
"GEYSERS",
"GIRAFFE",
"GIRAFFE",
"GLEANER",
"GLITTER",
"GNOCCHI",
"GNOCCHI",
"GO TO POT",
"GOBBLES",
"GODSEND",
"GRANITE",
"GRANITE",
"GRANITE",
"GRASSED",
"GRATING",
"GRAVITY",
"GREASER",
"GRENADA",
"GRENADE",
"GRIMACE",
"GRIMACE",
"GRIPPED",
"GROUNDS",
"GROW OLD",
"GUARDED",
"GUARDED",
"GUESSED",
"GUESSED",
"GYPSIES",
"HABITAT",
"HADDOCK",
"HADDOCK",
"HAIR-CUT",
"HAIR-OIL",
"HAIR-OIL",
"HAIRNET",
"HAIRPIN",
"HALF-WIT",
"HALTERS",
"HAMPERS",
"HAND-OUT",
"HAND-OUT",
"HAPLESS",
"HARBOUR",
"HARD SET",
"HARD-SET",
"HARNESS",
"HARNESS",
"HARPIST",
"HAS-BEEN",
"HASTIER",
"HAYSEED",
"HEADING",
"HEARING",
"HEARSAY",
"HEARTEN",
"HEATHER",
"HEATHER",
"HEAVE TO",
"HEIRESS",
"HEIRESS",
"HEROINE",
"HERONRY",
"HIDE-OUT",
"HIDEOUT",
"HIGH HAT",
"HITCHES",
"HOBNAIL",
"HOLDS UP",
"HOMESTEAD",
"HONOURS",
"HOODLUM",
"HOSTESS",
"HOSTESS",
"HOSTILE",
"HOTPOTS",
"HOUDINI",
"HUMERUS",
"HUMERUS",
"HUMOURS",
"HUNGARY",
"HUNGARY",
"HUNGARY",
"HURDLER",
"ICICLES",
"IDYLLIC",
"IGNOBLE",
"ILL-USED",
"ILLICIT",
"IMAGINE",
"IMAGINE",
"IMITATE",
"IMMENSE",
"IMMERSE",
"IMMERSE",
"IMPARTS",
"IMPEACH",
"IMPETUS",
"IMPINGE",
"IMPLIED",
"IMPLIES",
"IMPOSED",
"IMPRESS",
"IMPRINT",
"IMPRINT",
"IMPRINT",
"IN A WORD",
"IN DEPTH",
"INANELY",
"INBOARD",
"INCENSE",
"INCENSE",
"INCENSE",
"INCENSE",
"INCENSE",
"INCENSE",
"INCENSE",
"INCENSE",
"INCITED",
"INCITED",
"INDIANA",
"INDIANA",
"INERTIA",
"INERTIA",
"INERTIA",
"INERTIA",
"INFANCY",
"INFANCY",
"INFANCY",
"INFANTS",
"INFERNO",
"INFERNO",
"INFIDEL",
"INFORMS",
"INGRESS",
"INHABIT",
"INHERIT",
"INHERIT",
"INITIAL",
"INMATES",
"INROADS",
"INROADS",
"INSIDER",
"INSIDER",
"INSIGHT",
"INSIGHT",
"INSIGHT",
"INSIGHT",
"INSIGHT",
"INSIPID",
"INSPIRE",
"INSTALL",
"INSTANT",
"INSTEAD",
"INSTEAD",
"INSTEAD",
"INSULAR",
"INSULIN",
"INTENSE",
"INTENSE",
"INTENSE",
"INTERIM",
"INTERNS",
"INTRUDE",
"INUTILE",
"INVADER",
"INVENTS",
"INVENTS",
"INVENTS",
"INVERSE",
"INVERSE",
"INVOICE",
"IRELAND",
"ISHMAEL",
"ISOLATE",
"ISOLATE",
"ISTHMUS",
"ITEMISE",
"ITEMISE",
"ITEMISE",
"JANITOR",
"JAY-WALKERS",
"JESTING",
"KEENEST",
"KETCHUP",
"KIDNAPS",
"KINDRED",
"KING-PIN",
"KNOCKER",
"KNOWING",
"LACKING",
"LACONIC",
"LADDERS",
"LAGGARD",
"LAID OFF",
"LAID OUT",
"LANDING",
"LANTERN",
"LANTERN",
"LARCENY",
"LARIATS",
"LARIATS",
"LASCARS",
"LAST OUT",
"LAWYERS",
"LEAD OFF",
"LEADING",
"LEANDER",
"LEARNER",
"LEARNER",
"LEARNER",
"LEASHED",
"LEATHER",
"LEATHER",
"LEAVING",
"LEE-SIDE",
"LEGATEE",
"LEGENDS",
"LEISURE",
"LEISURE",
"LENIENT",
"LEONORA",
"LEOPARD",
"LESIONS",
"LET-DOWN",
"LETS OFF",
"LETTUCE",
"LETTUCE",
"LETTUCE",
"LEVERET",
"LEVERET",
"LEVERET",
"LIBERAL",
"LIBERAL",
"LICENSE",
"LICENSE",
"LICKING",
"LIGHTER",
"LIGHTER",
"LIGHTER",
"LIGHTER",
"LIGHTER",
"LIGHTLY",
"LIGNITE",
"LINCOLN",
"LINCOLN",
"LINE-OUT",
"LINEAGE",
"LINEAGE",
"LININGS",
"LIONESS",
"LISTENS",
"LISTENS",
"LISTING",
"LIVEN UP",
"LOATHED",
"LOITERS",
"LOOK-OUT",
"LOOK-OUT",
"LOOKOUT",
"LOOKS AT",
"LOOKS IN",
"LOOKS IN",
"LOOSELY",
"LOOSEST",
"LOTTERY",
"LOUDEST",
"LOW-DOWN",
"LOW-DOWN",
"LOWERED",
"LUCERNE",
"LUCHNOW",
"LUCIFER",
"LUNATIC",
"LYRICS",
"MACHETE",
"MADEIRA",
"MADEIRA",
"MADIERA",
"MAESTRO",
"MAESTRO",
"MAESTRO",
"MAGENTA",
"MAGNETO",
"MAINTOP",
"MAJESTY",
"MAKE WAY",
"MALTESE",
"MANACLE",
"MANACLE",
"MANAGED",
"MANAGES",
"MANDATE",
"MANDATE",
"MANDATE",
"MANKIND",
"MANKIND",
"MANNERS",
"MANNERS",
"MANXMAN",
"MARCHER",
"MARGINS",
"MARINER",
"MARINER",
"MARINER",
"MARINER",
"MARINES",
"MARRIED",
"MARSHAL",
"MARSHAL",
"MARTIAL",
"MARTINET",
"MARTINI",
"MARXIST",
"MASCOTS",
"MASONRY",
"MASONRY",
"MASSIVE",
"MASTERY",
"MASTERY",
"MASTIFF",
"MATCHES",
"MATCHES",
"MATCHES",
"MATCHES",
"MATELOT",
"MATELOT",
"MATELOT",
"MEASURE",
"MEASURE",
"MEISSEN",
"MESSAGE",
"METHANE",
"METHANE",
"MIDWIFE",
"MIDWIFE",
"MINARET",
"MINIMUM",
"MINIMUM",
"MINSTER",
"MINSTER",
"MISLEAD",
"MISS OUT",
"MISSAID",
"MISSION",
"MISSIVE",
"MISTAKE",
"MISTAKE",
"MISUSED",
"MODESTE",
"MODESTY",
"MODISTE",
"MODISTE",
"MOLOTOV",
"MONARCH",
"MORALLY",
"MOROCCO",
"MOROCCO LEATHER",
"MORSELS",
"MUFFLER",
"MUSICAL",
"MUSTANG",
"MUSTARD",
"NAILING",
"NAILING",
"NAILING",
"NAIROBI",
"NAIVITE",
"NANKEEN",
"NARRATE",
"NASCENT",
"NASTIER",
"NATURAL",
"NATURAL",
"NEAREST",
"NECKTIE",
"NECKTIE",
"NECKTIE",
"NECKTIE",
"NEEDLED",
"NEGLECT",
"NEGLECT",
"NEITHER",
"NEPTUNE",
"NEPTUNE",
"NESCENT",
"NESTING",
"NETTLED",
"NEUTRON",
"NEUTRON",
"NEUTRON",
"NEW-LAID",
"NEWGATE",
"NEXISIS",
"NIAGARA",
"NIAGARA",
"NIGERIA",
"NIGERIA",
"NITRATE",
"NITRATE",
"NO DOUBT",
"NOBLEST",
"NOISOME",
"NOISOME",
"NON-STOP",
"NONPLUS",
"NORMANS",
"NORWICH",
"NOSTRUM",
"NOSTRUM",
"NOTABLE",
"NOTABLE",
"NOTABLE",
"NOTABLE",
"NOTHING",
"NOTHING",
"NOTICES",
"NOTICES",
"NOVICES",
"NOVICES",
"NOWHERE",
"NUGGETS",
"NUMBERS",
"NUMERAL",
"NUMERAL",
"NUNNERY",
"NURSERY",
"NURSERY",
"NURSERY",
"NUTCASE",
"OARSMAN",
"OARSMEN",
"OARSMEN",
"OATMEAL",
"OBSERVE",
"OBSERVE",
"OBSERVE",
"OBSERVE",
"OBSERVE",
"OBSERVE",
"OCTOBER",
"OCTOPUS",
"OCULIST",
"ODD WORD",
"ODDMENT",
"ODDMENT",
"ODOROUS",
"OFF-HAND",
"OFFENCE",
"OFFENCE",
"OFFHAND",
"OFFICER",
"OIL-WELL",
"OLD IRON",
"OLD IRON",
"ON BOARD",
"ON WATCH",
"ONE-EYED",
"ONESELF",
"ONTARIO",
"ONTARIO",
"ONTARIO",
"ONTARIO",
"OPALINE",
"OPEN AIR",
"OPEN AIR",
"OPEN OUT",
"OPEN-AIR",
"OPEN-AIR",
"OPEN-AIR",
"OPERATE",
"OPERATE",
"OPERATE",
"OPHELIA",
"OPIATES",
"OPINION",
"OPPOSER",
"OPPRESS",
"OPPRESS",
"OPULENT",
"ORACLES",
"ORATION",
"ORATION",
"ORATORS",
"ORATORY",
"ORATORY",
"ORATORY",
"ORDEALS",
"ORDEALS",
"ORDERED",
"ORDINAL",
"OREGANO",
"OREGANO",
"ORGANIC",
"ORPHANS",
"ORPHANS",
"OSTRICH",
"OTTOMAN",
"OUTCOME",
"OUTDOOR",
"OUTDOOR",
"OUTFLOW",
"OUTLINE",
"OUTLINE",
"OUTLIVE",
"OUTLIVE",
"OUTPOST",
"OUTPOST",
"OUTPOST",
"OUTRAGE",
"OUTSIDE",
"OUTSIZE",
"OUTWARD",
"OUTWARD",
"OVERACT",
"OVERACT",
"OVERACT",
"OVEREAT",
"OVERSEA",
"OVERSEE",
"OXIDATE",
"PACIFIC",
"PAGEANT",
"PAINTER",
"PAINTER",
"PALADIN",
"PALETTE",
"PALMIST",
"PAPERED",
"PAPERER",
"PAPYRUS",
"PARAGON",
"PARASOL",
"PARENTS",
"PARLEYS",
"PARTIAL",
"PARTIAL",
"PARTIAL",
"PARTIAL",
"PARTIAL",
"PARTIAL",
"PARTIAL",
"PASSION",
"PASSION",
"PASTIME",
"PASTIME",
"PATELLA",
"PATRIOT",
"PAYMENT",
"PEASANT",
"PEERESS",
"PELICAN",
"PELICAN",
"PENALLY",
"PENANCE",
"PENANCE",
"PENSION SCHEME",
"PENSIVE",
"PEPPERS",
"PERFORM",
"PERFORM",
"PERSIST",
"PERSIST",
"PERTAIN",
"PERTURB",
"PERTURB",
"PESETAS",
"PETINIA",
"PICKLED",
"PICKLES",
"PICTURE",
"PINK-EYE",
"PIONEER",
"PIRATES",
"PITCHER",
"PITCHER",
"PITFALL",
"PITFALL",
"PLACATE",
"PLANETS",
"PLANETS",
"PLATEAU",
"PLAYBOY",
"PLIABLE",
"PLIGHTS",
"PLOTTER",
"PLUMBER",
"POINTER",
"POINTER",
"POLECAT",
"POMPEII",
"PONTOON",
"PORTION",
"POSSESS",
"POTHOLE",
"POTHOLE",
"POTIONS",
"POTIONS",
"POTTERS",
"POTTING",
"PRECISE",
"PREDICT",
"PREFACE",
"PRELATE",
"PRELATE",
"PRELUDE",
"PREPARE",
"PRESENT",
"PRESENT",
"PRESENT",
"PRESENT",
"PRESENT",
"PRESENT",
"PRESENT",
"PRESIDE",
"PRESS ON",
"PRESS-UP",
"PRESUME",
"PRINTER",
"PRINTER",
"PRINTER",
"PRISON",
"PRIVATE",

"PRIVATE",
"PRO RATA",
"PROCEED",
"PRODUCT",
"PROFFER",
"PROFILE",
"PROPHET",
"PROPHET",
"PROPHET",
"PROPHET",
"PROPHET",
"PROPOSE",
"PROPOSE",
"PROTEST",
"PROTEST",
"PROTEST",
"PROVIDE",
"PROWESS",
"PRURIGO",
"PUBLISH",
"PUNTERS",
"PURPOSE",
"PUT BACK",
"PUT DOWN",
"PYJAMAS",
"PYJAMAS",
"RABBITS",
"RACKETS",
"RACKETS",
"RADIATE",
"RAFFISH",
"RAFFLES",
"RAGTIME",
"RAGTIME",
"RAIL-CAR",
"RAILING",
"RAILWAY",
"RAILWAY STATION",
"RAIMENT",
"RAIMENT",
"RAMBLER",
"RAMPART",
"RANCHER",
"RANGOON",
"RANGOON",
"RANGOON",
"RANKLED",
"RAPPORT",
"RAPPORT",
"RAW DEAL",
"RE-ENACT",
"RE-ENACT",
"REACTOR",
"REACTOR",
"REACTOR",
"READERS",
"REAFERS",
"REALISE",
"REALISE",
"REALISE",
"REALISM",
"REALIST",
"REALIST",
"REALIST",
"REALITY",
"REARING",
"REBOUND",
"REBOUND",
"REBOUND",
"REBOUND",
"REBUILT",
"RECEDES",
"RECEIVE",
"RECITED",
"RECLAIM",
"RECLUSE",
"RECLUSE",
"RECORDS",
"RECORDS",
"RECOUNT",
"RECOUNT",
"RECOVER",
"RECTORY",
"RED HERRING",
"REDRESS",
"REEFERS",
"REFLECT",
"REFLECT",
"REFORMS",
"REFUSAL",
"REFUSAL",
"REFUSAL",
"REGALIA",
"REGARDS",
"REGIMEN",
"REGULAR",
"REGULAR",
"REISSUE",
"REISSUE",
"REISSUE",
"REJOINS",
"RELAPSE",
"RELAPSE",
"RELAXED",
"RELEASE",
"RELOADS",
"REMAINS",
"REMNANT",
"REMORSE",
"REMOVED",
"REMOVED",
"REPAIRS",
"REPAIRS",
"REPLACE",
"REPLACE",
"REPLETE",
"REPORTS",
"REPROOF",
"REQUEST",
"REQUEST",
"RESDOUBT",
"RESENTS",
"RESERVE",
"RESERVE",
"RESERVE",
"RESERVE",
"RESERVE",
"RESIDES",
"RESIGNS",
"RESOLVE",
"RESORTS",
"RESOUND",
"RESOUND",
"RESPECT",
"RESUMES",
"RESUMES",
"RETINUE",
"RETRACE",
"RETREAT",
"RETREAT",
"RETREAT",
"REVEALS",
"REVEALS",
"REVENGE",
"REVENGE",
"REVENUE",
"REVENUE",
"REVERIE",
"REVERSE",
"REVERSE",
"REVERSE",
"REVILED",
"REVIVAL",
"REWARDS",
"RING OFF",
"RIPOSTE",
"RISOTTO",
"RIVIERA",
"RIVIERA",
"RIVIERA",
"ROADMAN",
"ROGUERY",
"ROISTER",
"ROLLERS",
"ROMANCE",
"ROMANCE",
"ROMULUS",
"ROOKERY",
"ROOSTER",
"ROSETTE",
"ROSETTE",
"ROTATES",
"ROUTINE",
"ROWDIES",
"ROWDIES",
"RUDDERS",
"RUN DOWN",
"RUN DOWN",
"RUN DOWN",
"RUNCTION",
"RUNNING",
"RUSH MAT",
"RUSSIAN",
"RUSSIAN",
"RUSTICS",
"RUSTLES",
"RUSTLES",
"SADDENS",
"SADDEST",
"SADISTS",
"SAFARIS",
"SALADIN",
"SALERNO",
"SALERNO",
"SALIENT",
"SALIENT",
"SALIENT",
"SALIENT",
"SALIENT",
"SALIENT",
"SALIENT",
"SALIENT",
"SALLIED",
"SALTIRE",
"SANDALS",
"SARACEN",
"SARDINE",
"SARDINE",
"SATANIC",
"SATCHEL",
"SATISFY",
"SATISFY",
"SAW-MILL",
"SCANDAL",
"SCARLET",
"SCARVES",
"SCEPTIC",
"SCHERZO",
"SCIENCE",
"SCIENCE",
"SCISSOR",
"SCOURED",
"SCOURED",
"SCRAPED",
"SCRAPER",
"SCRATCH",
"SCRATCH",
"SCRATCH",
"SCREECH",
"SCREECH",
"SCREECH",
"SCREENS",
"SCRIBES",
"SCRUMPY",
"SCRUPLE",
"SCRUPLE",
"SCUPPER",
"SCUTTLE",
"SEA MIST",
"SEA-WALL",
"SEALING",
"SEALING",
"SEASIDE",
"SEASONS",
"SEAWEED",
"SECRET",
"SECRETE",
"SECRETE",
"SECRETE",
"SECRETE",
"SECTION",
"SEIZURE",
"SELFISH",
"SEMINAR",
"SENATOR",
"SENATOR",
"SENATOR",
"SENDING",
"SERAPHS",
"SERMONS",
"SESSION",
"SESSION",
"SET BACK",
"SET FAIR",
"SET PLAN",
"SET PLAN",
"SET UPON",
"SET-BACK",
"SETTIES",
"SETTLER",
"SETTLER",
"SETTLES",
"SETTLES",
"SEVERAL",
"SEVERED",
"SHALLOW",
"SHARING",
"SHATTER",
"SHEARED",
"SHEARED",
"SHIVERS",
"SHOWMAN",
"SHRIEKS",
"SHUTS UP",
"SHUTTLE",
"SIDECAR",
"SIGNALS",
"SIGNORA",
"SILENCE",
"SINCERE",
"SINGLET",
"SINGLET",
"SINGLET",
"SINKING",
"SKEWERS",
"SKIPPER",
"SKUTTLE",
"SLAKING",
"SLATERS",
"SLEIGHT",
"SLIDING",
"SLIPPER",
"SLIPPER",
"SLOWEST",
"SMARTER",
"SNIFFED",
"SOAKING",
"SOLDIER",
"SOLICIT",
"SOLOMON",
"SOMEONE",
"SOMEONE",
"SOMEONE",
"SOPRANO",
"SOPRANO",
"SOPRANO",
"SOUNDER",
"SPANIEL",
"SPANNER",
"SPECIAL",
"SPECIAL",
"SPECIAL",
"SPECIES",
"SPECTRE",
"SPIN-OFF",
"SPIRALS",
"SPIRITS",
"SPIRITS",
"SPLAYED",
"SPOTTED",
"SPOTTED",
"SPRINGE",
"SPRINGS",
"SPROUTS",
"SPROUTS",
"SQUARED",
"STAGING",
"STAINED",
"STANCES",
"STAND UP",
"STAND-IN",
"STAPLER",
"STARDOM",
"STARING",
"STARTER",
"STARTLE",
"STATING",
"STEALTH",
"STEAMER",
"STEEPLE",
"STENCIL",
"STENCIL",
"STENCIL",
"STEPSON",
"STERILE",
"STIFFEN",
"STILTED",
"STILTED",
"STIRRER",
"STIRRUP",
"STIRRUP",
"STOPPED",
"STORAGE",
"STORAGE",
"STORAGE",
"STORIES",
"STORIES",
"STRAITS",
"STRANDS",
"STRAYED",
"STREAKS",
"STRETCH",
"STRETCH",
"STRETCH",
"STRIDES",
"STRIDES",
"STRIKER",
"STRIPES",
"STROKES",
"STROKES",
"STROLLS",
"STROLLS",
"STUDENT",
"STUDENT",
"STUDENT",
"STUDIES",
"STUDIES",
"STUNTED",
"SUBLIME",
"SUBLIME",
"SUICIDE",
"SUMMARY",
"SUMMARY",
"SUMMITS",
"SURCOAT",
"SURFACE",
"SURGEON",
"SURGEON",
"SURNAME",
"SURNAME",
"SUSPECT",
"SUSTAIN",
"SUSTAIN",
"SWAHILI",
"SWAHILI",
"SWEETEN",
"TABLEAU",
"TACKING",
"TADPOLE",
"TAKES ON",
"TAKINGS",
"TAKINGS",
"TAKINGS",
"TALENTS",
"TALENTS",
"TANGIER",
"TANKARD",
"TANKARD",
"TANTRUM",
"TAPERED",
"TARIFFS",
"TARNISH",
"TARTARS",
"TASTIER",
"TASTIER",
"TATTLES",
"TEACAKE",
"TEATIME",
"TEL AVIV",
"TENABLE",
"TENABLE",
"TENANTS",
"TENFOLD",
"TENSION",
"TENSION",
"TENSION",
"TERRACE",
"TERRACE",
"TERRIER",
"TESTATE",
"TETANUS",
"TETHERS",
"TETHERS",
"TEXTURE",
"THEATRE",
"THEATRE",
"THEOREM",
"THERAPY",
"THERAPY",
"THERAPY",
"THERAPY",
"THERAPY",
"THERAPY",
"THEREIN",
"THERESA",
"THESEUS",
"THIMBLE",
"THIMBLE",
"THIMBLE",
"THIMBLE",
"TIBETAN",
"TICKETS",
"TIGRESS",
"TIGRESS",
"TIPPERS",
"TIRADES",
"TIRADES",
"TITANIC",
"TITLARK",
"TITLARK",
"TOADIES",
"TOBACCO",
"TOILERS",
"TOLL-BAR",
"TONGUES",
"TONGUES",
"TONIGHT",
"TONNAGE",
"TONNAGE",
"TOOK OUT",
"TOPIARY",
"TORNADO",
"TORNADO",
"TORNADO",
"TORPEDO",
"TORPEDO",
"TORRENT",
"TORRENT",
"TORSION",
"TOTALLY",
"TOUCH UP",
"TOUCH UP",
"TOUCHED",
"TOURING",
"TRACTOR",
"TRADUCE",
"TRAFFIC",
"TRAGEDY",
"TRAGEDY",
"TRAINER",
"TRAINER",
"TRANSIT",
"TRANSIT",
"TRAPEZE",
"TRAVAIL",
"TREACLE",
"TREACLE",
"TREADLE",
"TREADLE",
"TREASON",
"TREASON",
"TREASON",
"TREATED",
"TREMOLO",
"TREMOLO",
"TREMOLO",
"TRESTLE",
"TRESTLE",
"TRICKLE",
"TRICKLE",
"TRIES ON",
"TRIMMER",
"TRINKET",
"TRIPOLI",
"TRIPOLI",
"TRIPOLI",
"TRIPPER",
"TRIPPER",
"TRIPS UP",
"TRIVIAL",
"TRIVIAL",
"TRIVIAL",
"TRIVIAL",
"TROOPER",
"TROPICS",
"TROUBLE",
"TROUBLE",
"TRUANCY",
"TRUSTEE",
"TRUSTEE",
"TRUSTEE",
"TSARINA",
"TUNEFUL",
"TUNEFUL",
"TUNISIA",
"TUNISIA",
"TURMOIL",
"TWIN-SET",
"TWISTER",
"TWISTER",
"TWOSOME",
"ULYSSES",
"UMPTEEN",
"UNARMED",
"UNCOVER",
"UNCURLS",
"UNDRESS",
"UNDRESS",
"UNEATEN",
"UNEQUAL",
"UNHORSE",
"UNICORN",
"UNIFORM",
"UNIFORM",
"UNIFORM",
"UNKEMPT",
"UNLOADS",
"UNLOOSE",
"UNNERVE",
"UNRAVEL",
"UNRAVEL",
"UNTRIED",
"UNTRIED",
"UNTRIED",
"UP TRAIN",
"UPSHOTS",
"UPSTART",
"USELESS",
"USELESS",
"USELESS",
"USELESS",
"USELESS",
"USURERS",
"USURPED",
"UTENSIL",
"VACCINE",
"VACCINE",
"VANDYKE",
"VANDYKE",
"VANILLA",
"VARNISH",
"VAULTED",
"VERANDA",
"VERBENA",
"VERBOSE",
"VERDICT",
"VERSION",
"VICIOUS",
"VIEWERS",
"VILLAIN",
"VILLAIN",
"VILLAIN",
"VILLIAN",
"VIOLATE",
"VISAGES",
"VISIONS",
"VISITOR",
"VISITOR",
"VULTURE",
"VULTURE",
"WARFARE",
"WARMEST",
"WASSAIL",
"WASTAGE",
"WASTREL",
"WEALTHY",
"WEALTHY",
"WEIGHTS",
"WESTERN",
"WHATNOT",
"WILD-CAT",
"WILD-CAT STRIKES",
"WILLING",
"WINSOME",
"WORSHIP",
"WORSTED",
"WORSTED",
"WRAITHS",
"WREATHS",
"WREATHS",
"WRINKLE",
"WRITHES",
"WRITTEN",
"YASHMAK",
"YEARNED",
"YSARINA",
"YULE LOG",
"YULE-LOG"

);
